DATA("阿悄-陪我去流浪","http://index.asia.ga/?/music/china/AQiao-PWQLL.mp3","1");
DATA("蔡依林-我知道你很难过","http://index.asia.ga/?/music/china/CaiYiLin-IKnowYouSad.mp3","2");
DATA("蔡依林-日不落","http://index.asia.ga/?/music/china/CaiYiLin-SunBL.mp3","3");
DATA("蔡依林-LOVE LOVE LOVE","http://index.asia.ga/?/music/china/CaiYiLin-LOVELOVELOVE.mp3","4");
DATA("蔡健雅-无底洞","http://index.asia.ga/?/music/china/CJY-WuDiDong.mp3","5");
DATA("陈百强-一生何求","http://index.asia.ga/?/music/china/ChenBQ-YSHQ.mp3","6");
DATA("陈百强-偏偏喜欢你","http://index.asia.ga/?/music/china/Chenbq-LikeYou.mp3","7");
DATA("陈楚生-有没有人告诉你","http://index.asia.ga/?/music/china/ChenCS-TellYou.mp3","8");
DATA("陈妃平-永远到底有多远","http://index.asia.ga/?/music/china/ChenFP-HowLang.mp3","9");
DATA("陈红-走过长安街","http://index.asia.ga/?/music/china/ChenHong-ChangANjie.mp3","10");
DATA("陈慧琳-记事本","http://index.asia.ga/?/music/china/ChenHL-NoteBook.mp3","11");
DATA("陈冠蒲-太多","http://index.asia.ga/?/music/china/ChenGP-TaiDuo.mp3","12");
DATA("陈冠蒲-就让你走","http://index.asia.ga/?/music/china/ChenGP-LetYouGo.mp3","13");
DATA("陈升 刘佳慧-北京一夜","http://index.asia.ga/?/music/china/ChenSH-OneNightInBeiJing.mp3","14");
DATA("陈淑桦-情关","http://index.asia.ga/?/music/china/ChenSH-QingGuan.mp3","15");
DATA("陈淑桦-梦醒时分","http://index.asia.ga/?/music/china/ChenSH-Mengxsf.mp3","16");
DATA("陈淑桦-笑红尘","http://index.asia.ga/?/music/china/ChenSH-Xiaohc.mp3","17");
DATA("陈奕迅-爱情转移","http://index.asia.ga/?/music/china/ChenYx-LoveMove.mp3","18");
DATA("陈奕迅-十年","http://index.asia.ga/?/music/china/ChenYx-10N.mp3","19");
DATA("成龙 金喜善-无尽的爱","http://index.asia.ga/?/music/china/ChengLong-LoveNoEnd.mp3","20");
DATA("崔子格-卜卦","http://index.asia.ga/?/music/china/CuiZG-BuGua.mp3","21");
DATA("刀郎-爱是你我","http://index.asia.ga/?/music/china/DaoLang-LoveYouMe.mp3","22");
DATA("邓紫棋-你把我灌醉","http://index.asia.ga/?/music/china/DengZQ-NiBWGZ.mp3","23");
DATA("邓紫棋-喜欢你","http://index.asia.ga/?/music/china/DengZQ-LoveYou.mp3","24");
DATA("邓紫棋-泡沫","http://index.asia.ga/?/music/china/DengZQ-PaoMo.mp3","25");
DATA("丁当-猜不透","http://index.asia.ga/?/music/china/DingDang-CaiBuTou.mp3","26");
DATA("范玮琪-最重要的决定","http://index.asia.ga/?/music/china/FanWQ-ZZYDJD.mp3","27");
DATA("飞儿乐团-千年之恋","http://index.asia.ga/?/music/china/FIR-1000YEARS.mp3","28");
DATA("凤飞飞-追梦人","http://index.asia.ga/?/music/china/FengFF-dream.mp3","29");
DATA("凤凰传奇-荷塘月色","http://index.asia.ga/?/music/china/FengHCQ-HeTYS.mp3","30");
DATA("凤凰传奇-郎的诱惑","http://index.asia.ga/?/music/china/FengHCQ-LangDYH.mp3","31");
DATA("高安,黑鸭子-红尘情歌","http://index.asia.ga/?/music/china/GaoAN-LoveSong.mp3","32");
DATA("格格-火苗","http://index.asia.ga/?/music/china/GeGe-fire.mp3","33");
DATA("贡维特-想你想到眼泪流","http://index.asia.ga/?/music/china/Gongweite-xnxdyll.mp3","34");
DATA("光良-童话","http://index.asia.ga/?/music/china/GuangL-TongHua.mp3","35");
DATA("光良-都是你","http://index.asia.ga/?/music/china/GuangLiang-AllYou.mp3","36");
DATA("郭美美-爱情女神","http://index.asia.ga/?/music/china/GuoMM-LoveNS.mp3","37");
DATA("海鸣威-老人与海","http://index.asia.ga/?/music/china/HaiMW-OldMan.mp3","38");
DATA("韩红-天亮了","http://index.asia.ga/?/music/china/HanHong-Tianll.mp3","39");
DATA("韩红-天路","http://index.asia.ga/?/music/china/HanHong-TianLu.mp3","40");
DATA("韩雪-想起","http://index.asia.ga/?/music/china/HanXue-XiangQi.mp3","41");
DATA("浩瀚-分手在那个秋天","http://index.asia.ga/?/music/china/HaoHan-FenSZNGQT.mp3","42");
DATA("何璐-让她降落","http://index.asia.ga/?/music/china/HeLu-LetHerDown.mp3","43");
DATA("胡杨林-香水有毒","http://index.asia.ga/?/music/china/HuYL-XSYD.mp3","44");
DATA("黄小琥-没那么简单","http://index.asia.ga/?/music/china/HuangXH-MeiNMJD.mp3","45");
DATA("霍尊-卷珠帘","http://index.asia.ga/?/music/china/HunZun-JuanZL.mp3","46");
DATA("江美琪-亲爱的你怎么不在我身边","http://index.asia.ga/?/music/china/JiangMQ-NotByMe.mp3","47");
DATA("蒋雪儿-谁在意我留下的泪","http://index.asia.ga/?/music/china/Jxuer-WhyCareMe.mp3","48");
DATA("侃侃-滴答","http://index.asia.ga/?/music/china/KanKan-DiDa.mp3","49");
DATA("老狼-同桌的你","http://index.asia.ga/?/music/china/LaoLang-TZDN.mp3","50");
DATA("李彩桦-我爱雨天","http://index.asia.ga/?/music/china/LiCH-Rainday.mp3","51");
DATA("李慧珍-习惯","http://index.asia.ga/?/music/china/LiHuiZ-XG.mp3","52");
DATA("李玟-想你的365天","http://index.asia.ga/?/music/china/LiWen-365day.mp3","53");
DATA("李玟-月光爱人","http://index.asia.ga/?/music/china/LiWen-MoonLover.mp3","54");
DATA("李圣杰-痴心绝对","http://index.asia.ga/?/music/china/LiSJ-CXJD.mp3","55");
DATA("李圣杰-手放开","http://index.asia.ga/?/music/china/LiSJ-HandKAI.mp3","56");
DATA("李晓杰-朋友的酒","http://index.asia.ga/?/music/china/LiXJ-PYDJ.mp3","57");
DATA("李宇春-梨花香","http://index.asia.ga/?/music/china/LiYuC-LiHX.mp3","58");
DATA("李玉刚-新贵妃醉酒","http://index.asia.ga/?/music/china/LiYuG-XGFZJ.mp3","59");
DATA("李玉刚-菊花台","http://index.asia.ga/?/music/china/LiYuG-JuHT.mp3","60");
DATA("李玉刚-斯卡博罗集市","http://index.asia.ga/?/music/china/LiYuG-SiKBLJS.mp3","61");
DATA("梁静茹-可惜不是你","http://index.asia.ga/?/music/china/LiangJR-NotYou.mp3","62");
DATA("林宸希-不再问","http://index.asia.ga/?/music/china/LinZX-BuZW.mp3","63");
DATA("林心如-落花","http://index.asia.ga/?/music/china/LinXinRu-LuoHua.mp3","64");
DATA("林心如-倾听我","http://index.asia.ga/?/music/china/LinXinRu-QingTingWo.mp3","65");
DATA("林宥嘉-你是我的眼","http://index.asia.ga/?/music/china/LinYJ-YouMyEye.mp3","66");
DATA("刘德华&陈慧琳-我不够爱你","http://index.asia.ga/?/music/china/LiuDeH-LoveNotEnough.mp3","67");
DATA("刘若英-很爱很爱你","http://index.asia.ga/?/music/china/LiuRY-HenAhAIn.mp3","68");
DATA("刘诗诗-等你的季节","http://index.asia.ga/?/music/china/LiuSS-DNDJJ.mp3","69");
DATA("林志炫-没离开过","http://index.asia.ga/?/music/china/LinZX-MeiLKG.mp3","70");
DATA("林志炫-烟花易冷","http://index.asia.ga/?/music/china/LinZX-YanHYL.mp3","71");
DATA("刘珂矣-半壶纱","http://index.asia.ga/?/music/china/LiuKeYi-BanHS.mp3","72");
DATA("刘珂矣-风筝误","http://index.asia.ga/?/music/china/LiuKeYi-FengZW.mp3","73");
DATA("刘珂矣-芙蓉雨","http://index.asia.ga/?/music/china/LiuKeYi-FURY.mp3","74");
DATA("刘珂矣-暖山","http://index.asia.ga/?/music/china/LiuKeYi-NuanShan.mp3","75");
DATA("刘珂矣-缥缃醉","http://index.asia.ga/?/music/china/LiuKeYi-PiaoMZ.mp3","76");
DATA("刘珂矣-泼茶香","http://index.asia.ga/?/music/china/LiuKeYi-PoCX.mp3","77");
DATA("刘珂矣-忘尘谷","http://index.asia.ga/?/music/china/LiuKeYi-WangCG.mp3","78");
DATA("六哲-错错错","http://index.asia.ga/?/music/china/LiuZhe-Cuo3.mp3","79");
DATA("罗大佑-恋曲1990","http://index.asia.ga/?/music/china/LuoDaY-Love1990.mp3","80");
DATA("卢冠廷-一生所爱","http://index.asia.ga/?/music/china/LuGT-YiSSA.mp3","81");
DATA("马天宇-该死的温柔","http://index.asia.ga/?/music/china/MaTY-GSDWR.mp3","82");
DATA("马郁-下辈子如果我还记得你","http://index.asia.ga/?/music/china/MaYu-XBZHJDN.mp3","83");
DATA("马郁-一天死去一点","http://index.asia.ga/?/music/china/MaYu-YTSQYD.mp3","84");
DATA("慕容晓晓-爱情买卖","http://index.asia.ga/?/music/china/MuRXX-AiQingMM.mp3","85");
DATA("孟庭苇-冬季到台北来看雨","http://index.asia.ga/?/music/china/MengTW-Winter.mp3","86");
DATA("孟庭苇-风中有朵雨做的云","http://index.asia.ga/?/music/china/MengTW-Cloud.mp3","87");
DATA("孟庭苇-谁的眼泪在飞","http://index.asia.ga/?/music/china/MengTW-Tear.mp3","88");
DATA("莫文蔚 张洪量-广岛之恋","http://index.asia.ga/?/music/china/MoWenW-GDZL.mp3","89");
DATA("莫文蔚-盛夏的果实","http://index.asia.ga/?/music/china/MoWenW-SXDGS.mp3","90");
DATA("潘越云-我是不是你最疼爱的人","http://index.asia.ga/?/music/china/PanYueYun-WSBSNZTDR.mp3","91");
DATA("邱永传-十一年","http://index.asia.ga/?/music/china/QiuYC-11year.mp3","92");
DATA("沙宝亮-暗香","http://index.asia.ga/?/music/china/SaBL-AnX.mp3","93");
DATA("萨顶顶-万物生","http://index.asia.ga/?/music/china/SaDingDing-WanWuSH.mp3","94");
DATA("石头 李玉刚-雨花石","http://index.asia.ga/?/music/china/ShiTou-YuHuaSHi.mp3","95");
DATA("石头-坚强的石头","http://index.asia.ga/?/music/china/ShiTou-jqdst.mp3","96");
DATA("斯琴高丽-犯错","http://index.asia.ga/?/music/china/SiQGL-FanCuo.mp3","97");
DATA("苏芮-牵手","http://index.asia.ga/?/music/china/SuRui-QianSHou.mp3","98");
DATA("苏永康-爱一个人好难","http://index.asia.ga/?/music/china/SuYK-ANGRHN.mp3","99");
DATA("苏永康-男人不该让女人流泪","http://index.asia.ga/?/music/china/SuYK-NRBGRNRLL.mp3","100");
DATA("汤潮-美了美了","http://index.asia.ga/?/music/china/TangChao-MeiL.mp3","101");
DATA("陶晶莹-太委屈","http://index.asia.ga/?/music/china/TaiJY-TaiWQ.mp3","102");
DATA("汪苏泷-不分手的恋爱","http://index.asia.ga/?/music/china/JiangSL-BFSDLAI.mp3","103");
DATA("王强-你把爱情给了谁","http://index.asia.ga/?/music/china/WangQiang-YourLoveWho.mp3","104");
DATA("王蓉-爸爸妈妈","http://index.asia.ga/?/music/china/WangRong-BBMM.mp3","105");
DATA("王馨平-别问我是谁","http://index.asia.ga/?/music/china/WangXP-WHoAmI.mp3","106");
DATA("王娅-爱情错觉","http://index.asia.ga/?/music/china/WangYa-LoveCuoJue.mp3","107");
DATA("王铮亮-时间都去哪儿了","http://index.asia.ga/?/music/china/WangZL-Time.mp3","108");
DATA("乌兰托娅-套马杆","http://index.asia.ga/?/music/china/WuLanTY-TaoMaGan.mp3","109");
DATA("王菲 陈奕迅-因为爱情","http://index.asia.ga/?/music/china/WangFei-ForLove.mp3","110");
DATA("王菲-传奇","http://index.asia.ga/?/music/china/WangFei-ChuanQi.mp3","111");
DATA("王菲-笑忘书","http://index.asia.ga/?/music/china/WangFei-XWS.mp3","112");
DATA("王杰-伤心1999","http://index.asia.ga/?/music/china/WangJie-Sad1999.mp3","113");
DATA("王杰-为了爱梦一生","http://index.asia.ga/?/music/china/WangJie-Love.mp3","114");
DATA("王麟-伤不起","http://index.asia.ga/?/music/china/WangLin-ShangBQ.mp3","115");
DATA("乌达木-梦中的额吉","http://index.asia.ga/?/music/china/WuDaMu-MZDEJ.mp3","116");
DATA("西游降魔-儿歌三百首","http://index.asia.ga/?/music/china/XiYou-EGSBS.mp3","117");
DATA("希亚-心醉","http://index.asia.ga/?/music/china/XiYa-XinZui.mp3","118");
DATA("萧萧-倔强的坚强","http://index.asia.ga/?/music/china/XiaoX-JJDJQ.mp3","119");
DATA("萧亚轩-爱的主打歌","http://index.asia.ga/?/music/china/XiaoYX-LoveZDG.mp3","120");
DATA("小沈阳-都要好好的","http://index.asia.ga/?/music/china/XiaoSY-ALLgOOD.mp3","121");
DATA("谢军-心在跳情在烧","http://index.asia.ga/?/music/china/XieJun-XinZaiT.mp3","122");
DATA("谢雨欣-步步高","http://index.asia.ga/?/music/china/XieYuX-BuBuG.mp3","123");
DATA("谢雨欣-第三天","http://index.asia.ga/?/music/china/XieYuX-3day.mp3","124");
DATA("谢雨欣-天仙子","http://index.asia.ga/?/music/china/XieYuX-TXZ.mp3","125");
DATA("信乐团-假如","http://index.asia.ga/?/music/china/XinYueT-JiaRu.mp3","126");
DATA("信乐团-离歌","http://index.asia.ga/?/music/china/XinYueT-LiGe.mp3","127");
DATA("信乐团-海阔天空","http://index.asia.ga/?/music/china/XinYueT-HKTK.mp3","128");
DATA("徐怀钰-分飞","http://index.asia.ga/?/music/china/XuHY-FenFei.mp3","129");
DATA("徐千雅-彩云之南","http://index.asia.ga/?/music/china/XuQYa-CaiYunZN.mp3","130");
DATA("徐誉滕-等一分钟","http://index.asia.ga/?/music/china/XuYT-1Fenz.mp3","131");
DATA("许慧欣-七月七日晴","http://index.asia.ga/?/music/china/XuHuiX-7M7D.mp3","132");
DATA("许美静-城里的月光","http://index.asia.ga/?/music/china/XuMeiJ-CityMoon.mp3","133");
DATA("许美静-阳光总在风雨后","http://index.asia.ga/?/music/china/XuMeiJ-SunBRian.mp3","134");
DATA("许茹芸-独角戏","http://index.asia.ga/?/music/china/XuRuYun-DuJX.mp3","135");
DATA("许茹芸-泪海","http://index.asia.ga/?/music/china/XuRuYun-LeiHai.mp3","136");
DATA("许茹芸-日光机场","http://index.asia.ga/?/music/china/XuRuYun-RiGJC.mp3","137");
DATA("许茹芸-如果云知道","http://index.asia.ga/?/music/china/XuRuYun-RuGYZD.mp3","138");
DATA("央金兰泽-遇上你是我的缘","http://index.asia.ga/?/music/china/YJLZ-YJNSWDY.mp3","139");
DATA("严艺丹-三寸天堂","http://index.asia.ga/?/music/china/YanYiDan-3CunTT.mp3","140");
DATA("严艺丹-等你的季节","http://index.asia.ga/?/music/china/YanYD-DengNDJJ.mp3","141");
DATA("杨坤-无所谓","http://index.asia.ga/?/music/china/YangKun-WuSuoWei.mp3","142");
DATA("杨培安-我相信","http://index.asia.ga/?/music/china/YangPeian-IBelive.mp3","143");
DATA("杨培安-爱上你是一个错","http://index.asia.ga/?/music/china/YangPeian-ASNSYGC.mp3","144");
DATA("杨千桦-小城大事","http://index.asia.ga/?/music/china/YangQH-XiaoCDS.mp3","145");
DATA("杨宗纬 张碧晨-凉凉","http://index.asia.ga/?/music/china/YangZW-LiangLiang.mp3","146");
DATA("宇桐非-感动天感动地","http://index.asia.ga/?/music/china/YuTF-GDTGDD.mp3","147");
DATA("张柏芝-星语心愿","http://index.asia.ga/?/music/china/ZBZ-XYXY.mp3","148");
DATA("曾春年-最幸福的人","http://index.asia.ga/?/music/china/ZengCN-ZuiXFDR.mp3","149");
DATA("张国荣-倩女幽魂","http://index.asia.ga/?/music/china/ZhangGR-QianNYH.mp3","150");
DATA("张杰-这,就是爱","http://index.asia.ga/?/music/china/ZhangJ-ZheJSAi.mp3","151");
DATA("张靓颖-画心","http://index.asia.ga/?/music/china/ZhangLY-HuaXin.mp3","152");
DATA("张卫健-一辈子一场梦","http://index.asia.ga/?/music/china/ZWJ-YBZYCM.mp3","153");
DATA("张卫健-虚虚实实","http://index.asia.ga/?/music/china/ZWJ-XXSS.mp3","154");
DATA("张信哲-爱不留","http://index.asia.ga/?/music/china/ZHangXZ-LoveBL.mp3","155");
DATA("张信哲-某某某","http://index.asia.ga/?/music/china/ZHangXZ-MMM.mp3","156");
DATA("张学友-当我想起你","http://index.asia.ga/?/music/china/ZXY-DWXQN.mp3","157");
DATA("张芸京-偏爱","http://index.asia.ga/?/music/china/ZHangYunJ-PianAi.mp3","158");
DATA("张宇-一言难尽","http://index.asia.ga/?/music/china/ZhagngYu-YYNJ.mp3","159");
DATA("张镐哲-好男人","http://index.asia.ga/?/music/china/ZhangHZ-HaoNR.mp3","160");
DATA("张惠妹-听海","http://index.asia.ga/?/music/china/ZhangHM-TingHai.mp3","161");
DATA("张韶涵-潘朵拉","http://index.asia.ga/?/music/china/ZhangSH-PanDL.mp3","162");
DATA("赵咏华-最浪漫的事","http://index.asia.ga/?/music/china/ZYH-ZLMDS.mp3","163");
DATA("郑源-怎么会狠心伤害我","http://index.asia.ga/?/music/china/ZHengYuan-ZMHXSHW.mp3","164");
DATA("郑源-寒江雪","http://index.asia.ga/?/music/china/ZHengYuan-HanJX.mp3","165");
DATA("周迅-飘摇","http://index.asia.ga/?/music/china/ZX-PiaoY.mp3","166");
DATA("周治平-那一场风花雪月的故事","http://index.asia.ga/?/music/china/ZhouZP-NYCFHXYDGS.mp3","167");
DATA("庄心妍-以后的以后","http://index.asia.ga/?/music/china/ZhuangXY-YiHDYH.mp3","168");
DATA("庄心妍、祁隆-一万个舍不得","http://index.asia.ga/?/music/china/ZhuangXY-YiWGSBD.mp3","169");
DATA("印度音乐-吉米来吧","http://index.asia.ga/?/music/in/IN-JMLB.mp3","170");
DATA("印度音乐-奴里","http://index.asia.ga/?/music/in/IN-NL.mp3","171");
DATA("印度音乐-大悲咒","http://index.asia.ga/?/music/in/IN-DBZ.mp3","172");
DATA("印度音乐-酒吧dj音乐","http://index.asia.ga/?/music/in/IN-DJ.mp3","173");
DATA("印度音乐-情字路上","http://index.asia.ga/?/music/in/IN-QZLS.mp3","174");
DATA("印度音乐-天使之吻","http://index.asia.ga/?/music/in/IN-TSZW.mp3","175");
DATA("Meghna Mishra-Nachdi Phira","http://index.asia.ga/?/music/in/MeghnaMishra-NachdiPhira.mp3","176");
DATA("kiss-因为是女子","http://index.asia.ga/?/music/korea/Kiss-IMAGIRL.mp3","177");
DATA("rania-dr feel good","http://index.asia.ga/?/music/korea/rania-drfeelgood.mp3","178");
DATA("Dana-到世界尽头","http://index.asia.ga/?/music/korea/Dana-WorldEnd.mp3","179");
DATA("WAX-改变化装","http://index.asia.ga/?/music/korea/WAX-GBHZ.mp3","180");
DATA("WAX-渴望爱情","http://index.asia.ga/?/music/korea/WAX-KWAQ.mp3","181");
DATA("WAX-余情","http://index.asia.ga/?/music/korea/WAX-YUQ.mp3","182");
DATA("wonder girls-nobody","http://index.asia.ga/?/music/korea/wondergirls-nobody.mp3","183");
DATA("冬季恋歌-从开始到现在","http://index.asia.ga/?/music/korea/FromBeigin.mp3","184");
DATA("蓝色生死恋-祈祷","http://index.asia.ga/?/music/korea/QIDAO.mp3","185");
DATA("李秀英-AlsoILoveYou","http://index.asia.ga/?/music/korea/LXY-AlsoILoveYou.mp3","186");
DATA("李秀英-NEVERAGAIN","http://index.asia.ga/?/music/korea/LXY-NEVERAGAIN.mp3","187");
DATA("柳真-Cha Cha","http://index.asia.ga/?/music/korea/Liuz-ChaCha.mp3","188");
DATA("裴勇俊-My Memory","http://index.asia.ga/?/music/korea/MyMemory.mp3","189");
DATA("朴慧京-Rain","http://index.asia.ga/?/music/korea/PHJ-Rain.mp3","190");
DATA("淑熙-啦啦啦","http://index.asia.ga/?/music/korea/SHUX-LALALA.mp3","191");
DATA("严正花-都走吧","http://index.asia.ga/?/music/korea/YZH-AllGo.mp3","192");
DATA("玉珠铉-仲夏夜之梦","http://index.asia.ga/?/music/korea/YZX-ZXYZM.mp3","193");
DATA("中岛美嘉-雪華","http://index.asia.ga/?/music/japan/ZhongDaoMJ-XueHua.mp3","194");
DATA("azu-angel","http://index.asia.ga/?/music/japan/azu-angel.mp3","195");
DATA("滨崎步-fly high","http://index.asia.ga/?/music/japan/BQB-fly_high.mp3","196");
DATA("滨崎步-To Be","http://index.asia.ga/?/music/japan/BQB-To_Be.mp3","197");
DATA("初音未来-甩葱歌","http://index.asia.ga/?/music/japan/CYWL-SCG.mp3","198");
DATA("大冢爱-桃ノ花ビラ","http://index.asia.ga/?/music/japan/DZAI-PEACH.mp3","199");
DATA("谷村新司-风姿花传","http://index.asia.ga/?/music/japan/GCXS-FZHZ.mp3","200");
DATA("谷村新司-睡莲","http://index.asia.ga/?/music/japan/GCXS-SL.mp3","201");
DATA("少女时代-mr taxi","http://index.asia.ga/?/music/japan/SNSD-mrtaxi.mp3","202");
DATA("少女时代-the boys","http://index.asia.ga/?/music/japan/SNSD-theboys.mp3","203");
DATA("宇多田光-First_Love","http://index.asia.ga/?/music/japan/YDTG-First_Love.mp3","204");
DATA("focus-等待着你","http://index.asia.ga/?/music/th/Focus-WaitForYou.mp3","205");
DATA("lydia-为什么不接电话","http://index.asia.ga/?/music/th/lydia-NoCall.mp3","206");
DATA("sara-即使知道要见面","http://index.asia.ga/?/music/th/sara-JSZDYJM.mp3","207");
DATA("Sara-总好过难过","http://index.asia.ga/?/music/th/Sara-ZHGNG.mp3","208");
DATA("Zaza-Kuam Pid Tid Tua","http://index.asia.ga/?/music/th/Zaza-KuamPidTidTua.mp3","209");
DATA("泰国歌曲-慢嗨舞曲","http://index.asia.ga/?/music/th/TH-MH.mp3","210");
DATA("铁达尼号-my heart will go on","http://index.asia.ga/?/music/usa/XilINDA-MyHeartWillGoOn.mp3","211");
DATA("avril lavigne-i'm with you","http://index.asia.ga/?/music/usa/avrillavigne-i'mwithyou.mp3","212");
DATA("emilia-big_big_world","http://index.asia.ga/?/music/usa/emilia-big_big_world.mp3","213");
DATA("Lady gaga-Poker Face","http://index.asia.ga/?/music/usa/Ladygaga-PokerFace.mp3","214");
DATA("Yesterday Once More","http://index.asia.ga/?/music/usa/YesterdayOnceMore.mp3","215");
DATA("我的名字叫伊莲","http://index.asia.ga/?/music/usa/MyNameYiLian.mp3","216");
DATA("groove coverage-god is a girl ","http://index.asia.ga/?/music/usa/groovecoverage-godisagirl.mp3","217");
DATA("nana-lonely","http://index.asia.ga/?/music/usa/nana-lonely.mp3","218");
DATA("sarah connor-just one last dance","http://index.asia.ga/?/music/usa/sarahconnor-justonelastdance.mp3","219");
DATA("布兰妮-everytime","http://index.asia.ga/?/music/usa/BLN-everytime.mp3","220");
DATA("维塔斯-海豚音","http://index.asia.ga/?/music/usa/Wts-HTY.mp3","221");
DATA("adaro-Es_Ist_Ein_Schnee_Gefallen","http://index.asia.ga/?/music/kong/adaro-EsIstEinSchneeGefallen.mp3","222");
DATA("amy diamond-Heartbeats","http://index.asia.ga/?/music/kong/amydiamond-Heartbeats.mp3","223");
DATA("cara dillon-Craigie_Hill","http://index.asia.ga/?/music/kong/caradillon-Craigie_Hill.mp3","224");
DATA("dj okawari-luv_letter","http://index.asia.ga/?/music/kong/djokawari-luv_letter.mp3","225");
DATA("enya-Only_Time","http://index.asia.ga/?/music/kong/enya-Only_Time.mp3","226");
DATA("hayley westenra-never say goodbye","http://index.asia.ga/?/music/kong/hayleywestenra-neversaygoodbye.mp3","227");
DATA("卡洛儿-假如爱有天意","http://index.asia.ga/?/music/kong/KLER-JRAIYTY.mp3","228");
DATA("卡洛儿-写给海洋","http://index.asia.ga/?/music/kong/KLER-FORSEA.mp3","229");
DATA("萨拉布莱曼-斯卡布罗集市","http://index.asia.ga/?/music/kong/sarahbrightman-SKBLJS.mp3","230");
DATA("手嶌葵-the rose","http://index.asia.ga/?/music/kong/SYW-therose.mp3","231");
DATA("斯维特拉娜 斯维吉科娃-天使消逝的地方","http://index.asia.ga/?/music/kong/SWTLANA-ANGEL.mp3","232");
DATA("有里知花-I_Cry","http://index.asia.ga/?/music/kong/YLZH-I_Cry.mp3","233");
DATA("S E N 神思者-故宫的记忆","http://index.asia.ga/?/music/kong/SEN-GGDJY.mp3","234");
DATA("s.e.n.s-悲情城市","http://index.asia.ga/?/music/kong/SEN-BQCS.mp3","235");
DATA("神秘园-莲花","http://index.asia.ga/?/music/kong/SMY-LH.mp3","236");
DATA("断情殇","http://index.asia.ga/?/music/kong/DQSANG.mp3","237");
DATA("t.a.t.u-30_Minutes","http://index.asia.ga/?/music/kong/tatu-30_Minutes.mp3","238");
DATA("爱尔兰口哨女皇-爱尔兰画眉","http://index.asia.ga/?/music/kong/madden-aelhm.mp3","239");
DATA("乌鸦 片尾曲-月光石","http://index.asia.ga/?/music/kong/WY-Rurutia.mp3","240");
DATA("yiruma-雨的印记","http://index.asia.ga/?/music/kong/yiruma-RAIN.mp3","241");
DATA("YANI-和兰花在一起","http://index.asia.ga/?/music/kong/YANI-HLHZYQ.mp3","242");
DATA("喜多郎-飞天","http://index.asia.ga/?/music/kong/XDL-FLYSKY.mp3","243");
DATA("宫崎骏 龙猫-水晶音乐","http://index.asia.ga/?/music/kong/GQJ-SJYY.mp3","244");
DATA("久石让-天空之城","http://index.asia.ga/?/music/kong/JSR-SKYCITY.mp3","245");
DATA("班得瑞-安妮的仙境","http://index.asia.ga/?/music/kong/BDR-ANDXJ.mp3","246");
DATA("班得瑞-月光","http://index.asia.ga/?/music/kong/BDR-MOON.mp3","247");
DATA("班得瑞-非洲日落","http://index.asia.ga/?/music/kong/BDR-FZLR.mp3","248");
DATA("班得瑞-仙境","http://index.asia.ga/?/music/kong/BDR-XJ.mp3","249");
DATA("理查德 克莱德曼-出埃及记","http://index.asia.ga/?/music/kong/LCD-CAJJ.mp3","250");
DATA("理查德 克莱德曼-梦中的婚礼","http://index.asia.ga/?/music/kong/LCD-MZDHL.mp3","251");
DATA("理查德 克莱德曼-秋日私语","http://index.asia.ga/?/music/kong/LCD-QRSY.mp3","252");
DATA("理查德 克莱德曼-水边的阿狄丽娜","http://index.asia.ga/?/music/kong/LCD-SBDADLN.mp3","253");
DATA("理查德 克莱德曼-午后的旅行","http://index.asia.ga/?/music/kong/LCD-WHDLX.mp3","254");
DATA("理查德 克莱德曼-瓦妮莎的微笑","http://index.asia.ga/?/music/kong/LCD-wnsdwx.mp3","255");
DATA("理查德 克莱德曼-致爱丽丝","http://index.asia.ga/?/music/kong/LCD-ALICE.mp3","256");
