DATA("Chunyy-azsyx","http://index.asia.ga/?/cyy/cyy/Chunyy-azsyx.mp3","1");
DATA("Chunyy-安魂曲","http://index.asia.ga/?/cyy/cyy/chunyy-ahq.mp3","2");
DATA("Chunyy-安妮的歌","http://index.asia.ga/?/cyy/cyy/chunyy-andg.mp3","3");
DATA("Chunyy-宝贝珍之歌","http://index.asia.ga/?/cyy/cyy/chunyy-bbzzg.mp3","4");
DATA("Chunyy-沉睡的森林","http://index.asia.ga/?/cyy/cyy/chunyy-csdsl.mp3","5");
DATA("Chunyy-沉思曲","http://index.asia.ga/?/cyy/cyy/chunyy-csq.wma","6");
DATA("Chunyy-初恋的地方","http://index.asia.ga/?/cyy/cyy/chunyy-clddf.mp3","7");
DATA("Chunyy-春之声圆舞曲 古典钢琴","http://index.asia.ga/?/cyy/cyy/chunyy-czsywqgdgq.mp3","8");
DATA("Chunyy-大溪地清流 米奴哀舞","http://index.asia.ga/?/cyy/cyy/chunyy-dxdqlmnaw.wma","9");
DATA("Chunyy-第六感生死恋","http://index.asia.ga/?/cyy/cyy/chunyy-dlgssl.wma","10");
DATA("Chunyy-断情殇","http://index.asia.ga/?/cyy/cyy/chunyy-dqs.mp3","11");
DATA("Chunyy-飞鼠溪","http://index.asia.ga/?/cyy/cyy/chunyy-fsx.wma","12");
DATA("Chunyy-风的气息","http://index.asia.ga/?/cyy/cyy/chunyy-fdqx.mp3","13");
DATA("Chunyy-风中之尘","http://index.asia.ga/?/cyy/cyy/chunyy-fzzc.mp3","14");
DATA("Chunyy-格里格索尔维格之歌","http://index.asia.ga/?/cyy/cyy/chunyy-glgsewgzg.mp3","15");
DATA("Chunyy-和兰花在一起","http://index.asia.ga/?/cyy/cyy/chunyy-hlhzyq.wma","16");
DATA("Chunyy-很好听","http://index.asia.ga/?/cyy/cyy/chunyy-hht.mp3","17");
DATA("Chunyy-火宵之月","http://index.asia.ga/?/cyy/cyy/chunyy-hxzy.mp3","18");
DATA("Chunyy-卡布里的月光","http://index.asia.ga/?/cyy/cyy/chunyy-kbldyg.mp3","19");
DATA("Chunyy-卡农钢琴曲","http://index.asia.ga/?/cyy/cyy/chunyy-kngqq.mp3","20");
DATA("Chunyy-蓝色的爱","http://index.asia.ga/?/cyy/cyy/chunyy-lsda.mp3","21");
DATA("Chunyy-梁祝之化蝶 笛子","http://index.asia.ga/?/cyy/cyy/chunyy-lzzhddz.wma","22");
DATA("Chunyy-绵雪","http://index.asia.ga/?/cyy/cyy/chunyy-mx.mp3","23");
DATA("Chunyy-茉莉花","http://index.asia.ga/?/cyy/cyy/chunyy-mlh.mp3","24");
DATA("Chunyy-森林中的一天","http://index.asia.ga/?/cyy/cyy/chunyy-slzdyt.mp3","25");
DATA("Chunyy-似曾相识","http://index.asia.ga/?/cyy/cyy/chunyy-szxs.wma","26");
DATA("Chunyy-守护你的天使","http://index.asia.ga/?/cyy/cyy/chunyy-shndts.mp3","27");
DATA("Chunyy-树蛙之歌","http://index.asia.ga/?/cyy/cyy/chunyy-swzg.mp3","28");
DATA("Chunyy-水之轮回","http://index.asia.ga/?/cyy/cyy/chunyy-szlh.mp3","29");
DATA("Chunyy-天鹅湖","http://index.asia.ga/?/cyy/cyy/chunyy-teh.mp3","30");
DATA("Chunyy-万福玛丽亚","http://index.asia.ga/?/cyy/cyy/chunyy-wfmly.mp3","31");
DATA("Chunyy-我的海洋","http://index.asia.ga/?/cyy/cyy/chunyy-wdhy.wma","32");
DATA("Chunyy-西班牙斗牛士进行曲","http://index.asia.ga/?/cyy/cyy/chunyy-xbydnsjxq.mp3","33");
DATA("Chunyy-西藏的月","http://index.asia.ga/?/cyy/cyy/chunyy-xcdy.mp3","34");
DATA("Chunyy-昔日情怀","http://index.asia.ga/?/cyy/cyy/chunyy-xrqh.mp3","35");
DATA("Chunyy-夏日华尔兹","http://index.asia.ga/?/cyy/cyy/chunyy-xrhez.mp3","36");
DATA("Chunyy-乡间晚风","http://index.asia.ga/?/cyy/cyy/chunyy-xjwf.mp3","37");
DATA("Chunyy-相识也是缘份","http://index.asia.ga/?/cyy/cyy/chunyy-xsysyf.mp3","38");
DATA("Chunyy-小步舞曲","http://index.asia.ga/?/cyy/cyy/chunyy-xbwq.mp3","39");
DATA("Chunyy-小雨落在你脸上","http://index.asia.ga/?/cyy/cyy/chunyy-xylznls.mp3","40");
DATA("Chunyy-雪之梦","http://index.asia.ga/?/cyy/cyy/chunyy-xzm.mp3","41");
DATA("Chunyy-野鸟情歌","http://index.asia.ga/?/cyy/cyy/chunyy-ynqg.mp3","42");
DATA("Chunyy-印象之旅","http://index.asia.ga/?/cyy/cyy/chunyy-yxzl.mp3","43");
DATA("Chunyy-雨林深处","http://index.asia.ga/?/cyy/cyy/chunyy-ylsc.mp3","44");
DATA("Chunyy-雨中漫步","http://index.asia.ga/?/cyy/cyy/chunyy-yzmb.mp3","45");
DATA("Chunyy-月光下的凤尾竹","http://index.asia.ga/?/cyy/cyy/chunyy-ygxdfwz.mp3","46");
DATA("Chunyy-云淡风轻","http://index.asia.ga/?/cyy/cyy/chunyy-ydfq.wma","47");
DATA("Chunyy-只此一生","http://index.asia.ga/?/cyy/cyy/chunyy-zcys.mp3","48");
DATA("Chunyy-最终幻想","http://index.asia.ga/?/cyy/cyy/chunyy-zzhx.mp3","49");
DATA("Joanie madden-The level plain","http://index.asia.ga/?/cyy/cyy/joaniemadden-thelevelplain.mp3","50");
DATA("yiruma-雨的印记","http://index.asia.ga/?/cyy/cyy/yiruma-ydyj.wma","51");
DATA("爱尔兰风笛 漫步神秘园","http://index.asia.ga/?/cyy/cyy/aelfdmbsmy.wma","52");
DATA("爱尔兰口哨女皇madden-爱尔兰画眉","http://index.asia.ga/?/cyy/cyy/aelksnhmadden-aelhm.mp3","53");
DATA("班得瑞-chariots of fire","http://index.asia.ga/?/cyy/cyy/bdr-chariotsoffire.wma","54");
DATA("班得瑞-diamonds","http://index.asia.ga/?/cyy/cyy/bdr-diamonds.mp3","55");
DATA("班得瑞-EI condor pasa","http://index.asia.ga/?/cyy/cyy/bdr-eicondorpasa.mp3","56");
DATA("班得瑞-i want to know love is","http://index.asia.ga/?/cyy/cyy/bdr-iwanttoknowloveis.mp3","57");
DATA("班得瑞-i_swear","http://index.asia.ga/?/cyy/cyy/bdr-i_swear.wma","58");
DATA("班得瑞-imagine","http://index.asia.ga/?/cyy/cyy/bdr-imagine.mp3","59");
DATA("班得瑞-into red velvet","http://index.asia.ga/?/cyy/cyy/bdr-intoredvelvet.wma","60");
DATA("班得瑞-moment of fantasy","http://index.asia.ga/?/cyy/cyy/bdr-momentoffantasy.mp3","61");
DATA("班得瑞-one moment in time","http://index.asia.ga/?/cyy/cyy/bdr-onemomentintime.mp3","62");
DATA("班得瑞-tenderness","http://index.asia.ga/?/cyy/cyy/bdr-tenderness.mp3","63");
DATA("班得瑞-the sounds of silence","http://index.asia.ga/?/cyy/cyy/bdr-thesoundsofsilence.wma","64");
DATA("班得瑞-tim's lullaby","http://index.asia.ga/?/cyy/cyy/bdr-timslullaby.wma","65");
DATA("班得瑞-安妮的仙境","http://index.asia.ga/?/cyy/cyy/bdr-andxj.mp3","66");
DATA("班得瑞-变幻之风","http://index.asia.ga/?/cyy/cyy/bdr-bhzf.wma","67");
DATA("班得瑞-晨光","http://index.asia.ga/?/cyy/cyy/bdr-cg.wma","68");
DATA("班得瑞-初雪","http://index.asia.ga/?/cyy/cyy/bdr-cx.mp3","69");
DATA("班得瑞-春水","http://index.asia.ga/?/cyy/cyy/bdr-cs.wma","70");
DATA("班得瑞-春野","http://index.asia.ga/?/cyy/cyy/bdr-cy.mp3","71");
DATA("班得瑞-春野","http://index.asia.ga/?/cyy/cyy/bdr-cy.wma","72");
DATA("班得瑞-非洲日落","http://index.asia.ga/?/cyy/cyy/bdr-fzrl.wma","73");
DATA("班得瑞-风的呢喃","http://index.asia.ga/?/cyy/cyy/bdr-fdnn.wma","74");
DATA("班得瑞-海王星","http://index.asia.ga/?/cyy/cyy/bdr-hwx.wma","75");
DATA("班得瑞-火战车","http://index.asia.ga/?/cyy/cyy/bdr-hzc.mp3","76");
DATA("班得瑞-涟漪","http://index.asia.ga/?/cyy/cyy/bdr-ly.wma","77");
DATA("班得瑞-马可波罗","http://index.asia.ga/?/cyy/cyy/bdr-mkbl.mp3","78");
DATA("班得瑞-满天星","http://index.asia.ga/?/cyy/cyy/bdr-mtx.mp3","79");
DATA("班得瑞-秘密","http://index.asia.ga/?/cyy/cyy/bdr-mm.wma","80");
DATA("班得瑞-排箫 老鹰之歌","http://index.asia.ga/?/cyy/cyy/bdr-pxlyzg.wma","81");
DATA("班得瑞-清晨","http://index.asia.ga/?/cyy/cyy/bdr-qc.wma","82");
DATA("班得瑞-日光海岸","http://index.asia.ga/?/cyy/cyy/bdr-rgha.mp3","83");
DATA("班得瑞-天堂之门","http://index.asia.ga/?/cyy/cyy/bdr-ttzm.wma","84");
DATA("班得瑞-微风山谷","http://index.asia.ga/?/cyy/cyy/bdr-wfsg.mp3","85");
DATA("班得瑞-无止境的见识","http://index.asia.ga/?/cyy/cyy/bdr-wzjdjs.wma","86");
DATA("班得瑞-夏日华尔兹","http://index.asia.ga/?/cyy/cyy/bdr-xrhez.wma","87");
DATA("班得瑞-仙境","http://index.asia.ga/?/cyy/cyy/bdr-xj.wma","88");
DATA("班得瑞-依卡路斯的羽翼","http://index.asia.ga/?/cyy/cyy/bdr-yklsdyy.mp3","89");
DATA("班得瑞-忧郁的爱","http://index.asia.ga/?/cyy/cyy/bdr-yyda.mp3","90");
DATA("班得瑞-月光","http://index.asia.ga/?/cyy/cyy/bdr-yg.mp3","91");
DATA("班得瑞-追梦人","http://index.asia.ga/?/cyy/cyy/bdr-zmr.mp3","92");
DATA("班得瑞-紫蝴蝶","http://index.asia.ga/?/cyy/cyy/bdr-zhd.mp3","93");
DATA("班德瑞-巴格达的星星","http://index.asia.ga/?/cyy/cyy/bdr-bgddxx.mp3","94");
DATA("贝多芬-悲怆奏鸣曲","http://index.asia.ga/?/cyy/cyy/bdf-bczmq.mp3","95");
DATA("贝多芬-命运交响乐","http://index.asia.ga/?/cyy/cyy/bdf-myjxl.mp3","96");
DATA("贝多芬-田园交响曲","http://index.asia.ga/?/cyy/cyy/bdf-tyjxq.wma","97");
DATA("贝多芬-月光奏鸣曲","http://index.asia.ga/?/cyy/cyy/bdf-ygzmq.mp3","98");
DATA("杜普雷-殇","http://index.asia.ga/?/cyy/cyy/dpl-s.mp3","99");
DATA("宫崎骏 龙猫-水晶音乐","http://index.asia.ga/?/cyy/cyy/gqjlm-sjyl.mp3","100");
DATA("久石让-天空之城","http://index.asia.ga/?/cyy/cyy/jsr-tkzc.mp3","101");
DATA("凯文柯恩-走过绿意","http://index.asia.ga/?/cyy/cyy/kwke-zgly.wma","102");
DATA("浪客剑心-In Memories “A boy meets The Man”","http://index.asia.ga/?/cyy/cyy/lkjx-inmemoriesaboymeetstheman.mp3","103");
DATA("李斯特-钟","http://index.asia.ga/?/cyy/cyy/lst-z.mp3","104");
DATA("理查德 克莱德曼-爱的纪念","http://index.asia.ga/?/cyy/cyy/lcdkldm-adjn.mp3","105");
DATA("理查德 克莱德曼-爱的协奏曲","http://index.asia.ga/?/cyy/cyy/lcdkldm-adxzq.mp3","106");
DATA("理查德 克莱德曼-爱之梦","http://index.asia.ga/?/cyy/cyy/lcdkldm-azm.wma","107");
DATA("理查德 克莱德曼-出埃及记","http://index.asia.ga/?/cyy/cyy/lcdkldm-cajj.mp3","108");
DATA("理查德 克莱德曼-给母亲的信","http://index.asia.ga/?/cyy/cyy/lcdkldm-gmqdx.wma","109");
DATA("理查德 克莱德曼-海边的祈祷","http://index.asia.ga/?/cyy/cyy/lcdkldm-hbdqd.mp3","110");
DATA("理查德 克莱德曼-海边的星空","http://index.asia.ga/?/cyy/cyy/lcdkldm-hbdxk.wma","111");
DATA("理查德 克莱德曼-欢乐颂","http://index.asia.ga/?/cyy/cyy/lcdkldm-hls.wma","112");
DATA("理查德 克莱德曼-欢乐之歌","http://index.asia.ga/?/cyy/cyy/lcdkldm-hlzg.wma","113");
DATA("理查德 克莱德曼-蓝色的爱","http://index.asia.ga/?/cyy/cyy/lcdkldm-lsda.mp3","114");
DATA("理查德 克莱德曼-蓝色狂想曲","http://index.asia.ga/?/cyy/cyy/lcdkldm-lskxq.wma","115");
DATA("理查德 克莱德曼-罗密欧与朱丽叶","http://index.asia.ga/?/cyy/cyy/lcdkldm-lmoyzly.wma","116");
DATA("理查德 克莱德曼-玫瑰色的人生","http://index.asia.ga/?/cyy/cyy/lcdkldm-mgsdrs.mp3","117");
DATA("理查德 克莱德曼-梦中的婚礼","http://index.asia.ga/?/cyy/cyy/lcdkldm-mzdhl.mp3","118");
DATA("理查德 克莱德曼-梦中的鸟","http://index.asia.ga/?/cyy/cyy/lcdkldm-mzdn.mp3","119");
DATA("理查德 克莱德曼-秘密的庭院","http://index.asia.ga/?/cyy/cyy/lcdkldm-mmdty.mp3","120");
DATA("理查德 克莱德曼-乒乓之恋","http://index.asia.ga/?/cyy/cyy/lcdkldm-ppzl.wma","121");
DATA("理查德 克莱德曼-秋日私语","http://index.asia.ga/?/cyy/cyy/lcdkldm-qrsy.mp3","122");
DATA("理查德 克莱德曼-柔如彩虹","http://index.asia.ga/?/cyy/cyy/lcdkldm-rrch.wma","123");
DATA("理查德 克莱德曼-伤感乐曲","http://index.asia.ga/?/cyy/cyy/lcdkldm-sglq.wma","124");
DATA("理查德 克莱德曼-少女的祈祷","http://index.asia.ga/?/cyy/cyy/lcdkldm-sndqd.wma","125");
DATA("理查德 克莱德曼-水边的阿狄丽娜","http://index.asia.ga/?/cyy/cyy/lcdkldm-sbdadln.mp3","126");
DATA("理查德 克莱德曼-思乡曲","http://index.asia.ga/?/cyy/cyy/lcdkldm-sxq.wma","127");
DATA("理查德 克莱德曼-瓦妮莎的微笑","http://index.asia.ga/?/cyy/cyy/lcdkldm-wnsdwx.mp3","128");
DATA("理查德 克莱德曼-忘却的悲伤","http://index.asia.ga/?/cyy/cyy/lcdkldm-wqdbs.mp3","129");
DATA("理查德 克莱德曼-威尼斯之旅","http://index.asia.ga/?/cyy/cyy/lcdkldm-wnszl.mp3","130");
DATA("理查德 克莱德曼-午后的旅行","http://index.asia.ga/?/cyy/cyy/lcdkldm-whdlx.wma","131");
DATA("理查德 克莱德曼-星空","http://index.asia.ga/?/cyy/cyy/lcdkldm-xk.mp3","132");
DATA("理查德 克莱德曼-野花","http://index.asia.ga/?/cyy/cyy/lcdkldm-yh.wma","133");
DATA("理查德 克莱德曼-英雄交响曲","http://index.asia.ga/?/cyy/cyy/lcdkldm-yxjxq.mp3","134");
DATA("理查德 克莱德曼-永远爱你","http://index.asia.ga/?/cyy/cyy/lcdkldm-yyan.wma","135");
DATA("理查德 克莱德曼-致爱丽丝","http://index.asia.ga/?/cyy/cyy/lcdkldm-zals.wma","136");
DATA("绿钢琴 乐曲","http://index.asia.ga/?/cyy/cyy/lgqlq.mp3","137");
DATA("马克西姆-克罗地亚狂想曲","http://index.asia.ga/?/cyy/cyy/mkxm-kldykxq.wma","138");
DATA("马友友-天鹅 大提琴演奏","http://index.asia.ga/?/cyy/cyy/myy-tedtqyz.mp3","139");
DATA("莫扎特 c大调小星星变奏曲","http://index.asia.ga/?/cyy/cyy/mzt-cddxxxbzq.mp3","140");
DATA("莫扎特-安魂曲","http://index.asia.ga/?/cyy/cyy/mzt-ahq.mp3","141");
DATA("莫扎特-魔笛","http://index.asia.ga/?/cyy/cyy/mzt-md.mp3","142");
DATA("莫扎特-土耳其进行曲","http://index.asia.ga/?/cyy/cyy/mzt-teqjxq.mp3","143");
DATA("莫扎特-小步舞曲","http://index.asia.ga/?/cyy/cyy/mzt-xbwq.mp3","144");
DATA("莫扎特-摇篮曲","http://index.asia.ga/?/cyy/cyy/mzt-ylq.wma","145");
DATA("莫扎特-幽默曲","http://index.asia.ga/?/cyy/cyy/mzt-ymq.mp3","146");
DATA("齐普利安·波隆贝斯库-永恒的记忆","http://index.asia.ga/?/cyy/cyy/qplablbsk-yhdjy.wma","147");
DATA("犬夜叉-哀歌","http://index.asia.ga/?/cyy/cyy/qyc-ag.mp3","148");
DATA("犬夜叉-跨越时代的思念","http://index.asia.ga/?/cyy/cyy/qyc-kysddsn.mp3","149");
DATA("神秘园-莲花","http://index.asia.ga/?/cyy/cyy/smy-lh.wma","150");
DATA("神秘园-夜曲","http://index.asia.ga/?/cyy/cyy/smy-yq.mp3","151");
DATA("神秘园-夜曲","http://index.asia.ga/?/cyy/cyy/smy-yq.wma","152");
DATA("神秘园-月亮门","http://index.asia.ga/?/cyy/cyy/smy-ylm.mp3","153");
DATA("神秘园之歌-月亮门","http://index.asia.ga/?/cyy/cyy/smyzg-ylm.wma","154");
DATA("神思者-Project","http://index.asia.ga/?/cyy/cyy/ssz-project.mp3","155");
DATA("神思者-悲情城市","http://index.asia.ga/?/cyy/cyy/ssz-bqcs.mp3","156");
DATA("神思者-故宫的记忆","http://index.asia.ga/?/cyy/cyy/ssz-ggdjy.mp3","157");
DATA("神思者-海之女神","http://index.asia.ga/?/cyy/cyy/ssz-hzns.mp3","158");
DATA("舒伯特-圣母颂","http://index.asia.ga/?/cyy/cyy/sbt-sms.wma","159");
DATA("舒曼-梦幻曲","http://index.asia.ga/?/cyy/cyy/sm-mhq.wma","160");
DATA("威尔第 茶花女-普罗旺斯的陆地和海洋","http://index.asia.ga/?/cyy/cyy/wedchn-plwsdldhhy.mp3","161");
DATA("乌鸦 片尾曲-月光石 Rurutia","http://index.asia.ga/?/cyy/cyy/wypwq-ygsrurutia.mp3","162");
DATA("喜多郎-飞天","http://index.asia.ga/?/cyy/cyy/xdl-ft.wma","163");
DATA("喜多郎-菩提树","http://index.asia.ga/?/cyy/cyy/xdl-pts.mp3","164");
DATA("萧邦-幻想即兴曲","http://index.asia.ga/?/cyy/cyy/xb-hxjxq.mp3","165");
DATA("徐仁修-森林狂想曲","http://index.asia.ga/?/cyy/cyy/xrx-slkxq.wma","166");
DATA("姚斯婷-寂静之声","http://index.asia.ga/?/cyy/cyy/yst-jjzs.wma","167");
DATA("约翰 施特劳斯-溜冰圆舞曲","http://index.asia.ga/?/cyy/cyy/yhstls-lbywq.mp3","168");
DATA("约翰 施特劳斯-闲聊波尔卡","http://index.asia.ga/?/cyy/cyy/yhstls-xlbek.mp3","169");
DATA("约翰·施特劳斯-蓝色多瑙河","http://index.asia.ga/?/cyy/cyy/yhstls-lsdnh.mp3","170");
DATA("约翰·施特劳斯-维也纳森林的故事","http://index.asia.ga/?/cyy/cyy/yhstls-wynsldgs.mp3","171");
DATA("约纳森-杜鹃圆舞曲","http://index.asia.ga/?/cyy/cyy/yns-djywq.mp3","172");
DATA("宗次郎-故乡的原风景","http://index.asia.ga/?/cyy/cyy/zcl-gxdyfj.mp3","173");
DATA("001.半山听雨，放空自己（古琴）-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/001-bstyfkzj(gq)-wmcyl.m4a","174");
DATA("002.故乡风景，醉美画卷 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/002-gxfjzmhj-wmcyl.m4a","175");
DATA("003.静水禅音，返朴归真-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/003-jscyfpgz-wmcyl.m4a","176");
DATA("004.天籁之音，荡涤心灵 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/004-tlzyddxl-wmcyl.m4a","177");
DATA("005.心灵雨伞 — 轻音乐","http://index.asia.ga/?/cyy/wmcyy/005-xlys-qyl.m4a","178");
DATA("006.童年-纯音乐","http://index.asia.ga/?/cyy/wmcyy/006-tn-cyl.m4a","179");
DATA("007.易经—纯音乐","http://index.asia.ga/?/cyy/wmcyy/007-yj-cyl.m4a","180");
DATA("008.太极 — 纯音乐 （古琴）","http://index.asia.ga/?/cyy/wmcyy/008-tj-cyl(gq).m4a","181");
DATA("009.琵琶语-纯音乐","http://index.asia.ga/?/cyy/wmcyy/009-ppy-cyl.m4a","182");
DATA("010.夜曲(很伤感的纯音乐) - 神秘园","http://index.asia.ga/?/cyy/wmcyy/010-yq(hsgdcyl)-smy.m4a","183");
DATA("011.无悔 -李汉颖 （加长版）","http://index.asia.ga/?/cyy/wmcyy/011-wh-lhy(jcb).m4a","184");
DATA("012.和兰花在一起 — 雅尼","http://index.asia.ga/?/cyy/wmcyy/012-hlhzyq-yn.m4a","185");
DATA("013.纯音乐 - 昨日重现（钢琴）","http://index.asia.ga/?/cyy/wmcyy/013-cyl-zrcx(gq).m4a","186");
DATA("014.纯音乐 - 此情永不移（钢琴）","http://index.asia.ga/?/cyy/wmcyy/014-cyl-cqyby(gq).m4a","187");
DATA("015.纯音乐 - 高山流水 (古筝)","http://index.asia.ga/?/cyy/wmcyy/015-cyl-gsls(gz).m4a","188");
DATA("016.纯音乐 - 雪花神剑（萧）","http://index.asia.ga/?/cyy/wmcyy/016-cyl-xhsj(x).m4a","189");
DATA("017.寂静之声 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/017-jjzs-bdr.m4a","190");
DATA("018.走过绿意 - Kevin Kern","http://index.asia.ga/?/cyy/wmcyy/018-zgly-kevinkern.m4a","191");
DATA("019.安妮的仙境 - 轻音乐","http://index.asia.ga/?/cyy/wmcyy/019-andxj-qyl.m4a","192");
DATA("020.净化心灵的声音 - Karunesh","http://index.asia.ga/?/cyy/wmcyy/020-jhxldsy-karunesh.m4a","193");
DATA("021.岁月如歌 ——哼唱歌手","http://index.asia.ga/?/cyy/wmcyy/021-syrg-hcgs.m4a","194");
DATA("022.The Beginning (开始) - Ryran·Tomson","http://index.asia.ga/?/cyy/wmcyy/022-thebeginning(ks)-ryrantomson.m4a","195");
DATA("023.日晷之梦(电台背景音乐) ——纯音乐","http://index.asia.ga/?/cyy/wmcyy/023-rgzm(dtbjyl)-cyl.m4a","196");
DATA("024.好一朵美丽的茉莉花 - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/024-hydmldmlh-gqq.m4a","197");
DATA("025.梦里水乡 - 中国民乐","http://index.asia.ga/?/cyy/wmcyy/025-mlsx-zgml.m4a","198");
DATA("026.青花瓷 - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/026-qhc-gqq.m4a","199");
DATA("027.梦中的婚礼 - 理查德","http://index.asia.ga/?/cyy/wmcyy/027-mzdhl-lcd.m4a","200");
DATA("028.星空—理查德·克莱德曼（钢琴）","http://index.asia.ga/?/cyy/wmcyy/028-xk-lcdkldm(gq).m4a","201");
DATA("029.风之彩 绝对经典 - 陶笛排萧乐","http://index.asia.ga/?/cyy/wmcyy/029-fzcjdjd-tdpxl.m4a","202");
DATA("030.西风（排箫）芈月传 - 王备","http://index.asia.ga/?/cyy/wmcyy/030-xf(px)myc-wb.m4a","203");
DATA("031.人生最美初见时 - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/031-rszmcjs-gqq.m4a","204");
DATA("032.夏日香气 - 电视剧原声 (很好听的钢琴曲)","http://index.asia.ga/?/cyy/wmcyy/032-xrxq-dsjys(hhtdgqq).m4a","205");
DATA("033.森林幻想曲 - Bandari","http://index.asia.ga/?/cyy/wmcyy/033-slhxq-bandari.m4a","206");
DATA("034.传奇 (琴牵美人吟Ⅱ) - 段银莹","http://index.asia.ga/?/cyy/wmcyy/034-cq(qqmry2)-dyy.m4a","207");
DATA("035.一剪梅 - 中国民乐","http://index.asia.ga/?/cyy/wmcyy/035-yjm-zgml.m4a","208");
DATA("036.广陵散之笑傲江湖曲 —琴箫合奏)","http://index.asia.ga/?/cyy/wmcyy/036-glszxajhq-qxhz).m4a","209");
DATA("037.佛教音乐 - 菩提树","http://index.asia.ga/?/cyy/wmcyy/037-fjyl-pts.m4a","210");
DATA("038.你离开的真相 — 舒缓睡眠","http://index.asia.ga/?/cyy/wmcyy/038-nlkdzx-shsm.m4a","211");
DATA("039.罗密欧与朱丽叶-群星","http://index.asia.ga/?/cyy/wmcyy/039-lmoyzly-qx.m4a","212");
DATA("040.蝴蝶华尔兹(助眠) — 纯音乐","http://index.asia.ga/?/cyy/wmcyy/040-hdhez(zm)-cyl.m4a","213");
DATA("041.我心永恒 — 纯音乐","http://index.asia.ga/?/cyy/wmcyy/041-wxyh-cyl.m4a","214");
DATA("042.康妮的蝴蝶 — 纯音乐","http://index.asia.ga/?/cyy/wmcyy/042-kndhd-cyl.m4a","215");
DATA("043.A Simple Life (唯美小清新治愈系) - Brian Crain","http://index.asia.ga/?/cyy/wmcyy/043-asimplelife(wmxqxzyx)-briancrain.m4a","216");
DATA("044.古诗 (Greek Meditation) - 吉他排笛","http://index.asia.ga/?/cyy/wmcyy/044-gs(greekmeditation)-jtpd.m4a","217");
DATA("045.耳边私语 (Almost a Whisper) - Chris Phillips","http://index.asia.ga/?/cyy/wmcyy/045-ebsy(almostawhisper)-chrisphillips.m4a","218");
DATA("046.宽阔的海水 (The Water Is Wide) - David Nevue","http://index.asia.ga/?/cyy/wmcyy/046-kkdhs(thewateriswide)-davidnevue.m4a","219");
DATA("047.美好清晨 - Daveed","http://index.asia.ga/?/cyy/wmcyy/047-mhqc-daveed.m4a","220");
DATA("048.Forrest Gump 电影-阿甘正传》插曲 — 纯音乐","http://index.asia.ga/?/cyy/wmcyy/048-forrestgumpdy-agzc-cq-cyl.m4a","221");
DATA("049.茶茗-静心禅乐 (Flowing With The Tea) - Karunesh","http://index.asia.ga/?/cyy/wmcyy/049-cm-jxcl(flowingwiththetea)-karunesh.m4a","222");
DATA("050.绵雪 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/050-mx-cyl.m4a","223");
DATA("051.迷情仙境 - 轻音乐","http://index.asia.ga/?/cyy/wmcyy/051-mqxj-qyl.m4a","224");
DATA("052.神秘园之歌 - 钢琴","http://index.asia.ga/?/cyy/wmcyy/052-smyzg-gq.m4a","225");
DATA("053.胡伟立 - 市集","http://index.asia.ga/?/cyy/wmcyy/053-hwl-sj.m4a","226");
DATA("054.Bandari - 安妮的歌","http://index.asia.ga/?/cyy/wmcyy/054-bandari-andg.m4a","227");
DATA("055.忧伤的步美 - 名侦探柯南插曲","http://index.asia.ga/?/cyy/wmcyy/055-ysdbm-mztkncq.m4a","228");
DATA("056.美丽的神话 - 王崴","http://index.asia.ga/?/cyy/wmcyy/056-mldsh-ww.m4a","229");
DATA("057.无尽地平线 (Endless Horizon) - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/057-wjdpx(endlesshorizon)-bdr.m4a","230");
DATA("058.Adagio 柔板 - 神秘园","http://index.asia.ga/?/cyy/wmcyy/058-adagiorb-smy.m4a","231");
DATA("059.寂色 (绝美的小提琴曲) - 神秘园","http://index.asia.ga/?/cyy/wmcyy/059-js(jmdxtqq)-smy.m4a","232");
DATA("060.三个人的时光 (天之痕) - 吴欣睿","http://index.asia.ga/?/cyy/wmcyy/060-sgrdsg(tzh)-wxr.m4a","233");
DATA("061.舒伯特小夜曲 (世界名曲) - 舒伯特","http://index.asia.ga/?/cyy/wmcyy/061-sbtxyq(sjmq)-sbt.m4a","234");
DATA("062.偏偏喜欢你 (钢琴) - 赵海洋","http://index.asia.ga/?/cyy/wmcyy/062-ppxhn(gq)-zhy.m4a","235");
DATA("063.一切为了你 (Everything I Do) - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/063-yqwln(everythingido)-bdr.m4a","236");
DATA("064.望天 (来不及说我爱你插曲) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/064-wt(lbjswancq)-cyl.m4a","237");
DATA("065.蝶恋花 - 二胡版","http://index.asia.ga/?/cyy/wmcyy/065-dlh-ehb.m4a","238");
DATA("066.静静的雪 (Snow) - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/066-jjdx(snow)-bdr.m4a","239");
DATA("067.永远同在 - 八音盒","http://index.asia.ga/?/cyy/wmcyy/067-yytz-byh.m4a","240");
DATA("068.Wish (神思者的哀伤和唯美) - 神思者","http://index.asia.ga/?/cyy/wmcyy/068-wish(sszdashwm)-ssz.m4a","241");
DATA("069.一帘幽梦(古筝) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/069-ylym(gz)-cyl.m4a","242");
DATA("070.月光仙子 (Princess Of The Moon) - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/070-ygxz(princessofthemoon)-bdr.m4a","243");
DATA("071.孤独的巡礼 ，真实的自己-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/071-gddxlzsdzj-wmcyl.m4a","244");
DATA("072.风舞者 Windancer - 神秘园","http://index.asia.ga/?/cyy/wmcyy/072-fwzwindancer-smy.m4a","245");
DATA("073.出水莲 (古筝独奏) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/073-csl(gzdz)-cyl.m4a","246");
DATA("074.月光曲 - 贝多芬","http://index.asia.ga/?/cyy/wmcyy/074-ygq-bdf.m4a","247");
DATA("075.爱殇 - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/075-as-gqq.m4a","248");
DATA("076.优美动听古典音乐 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/076-ymdtgdyl-cyl.m4a","249");
DATA("077.中国古典音乐 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/077-zggdyl-cyl.m4a","250");
DATA("078.梦于月光中 (Dreaming In The Moonlight) - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/078-myygz(dreaminginthemoonlight)-bdr.m4a","251");
DATA("079.枉凝眉箫曲 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/079-wnmxq-cyl.m4a","252");
DATA("080.莎莉花园 (绿野仙踪) - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/080-slhy(lyxz)-bdr.m4a","253");
DATA("081.海王星 (Neptune) - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/081-hwx(neptune)-bdr.m4a","254");
DATA("082.天使情人 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/082-tsqr-cyl.m4a","255");
DATA("083.阿根廷别为我哭泣","http://index.asia.ga/?/cyy/wmcyy/083-agtbwwkq.m4a","256");
DATA("084.风动草( 陶笛) - 伴奏版","http://index.asia.ga/?/cyy/wmcyy/084-fdc(td)-bzb.m4a","257");
DATA("085.蝶舞娉婷 Papillon - 神秘园","http://index.asia.ga/?/cyy/wmcyy/085-dwptpapillon-smy.m4a","258");
DATA("086.你鼓舞了我 You Raise Me Up - 神秘园","http://index.asia.ga/?/cyy/wmcyy/086-ngwlwyouraisemeup-smy.m4a","259");
DATA("087.微风小径 (The Winding Path) - Kevin Kern","http://index.asia.ga/?/cyy/wmcyy/087-wfxj(thewindingpath)-kevinkern.m4a","260");
DATA("088.童年的味道 (轻快的纯音乐) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/088-tndwd(qkdcyl)-cyl.m4a","261");
DATA("089.Sometimes When It Rains (下雨的时候) - 神秘园","http://index.asia.ga/?/cyy/wmcyy/089-sometimeswhenitrains(xydsh)-smy.m4a","262");
DATA("090.倩女幽魂 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/090-qnyh-cyl.m4a","263");
DATA("091.蒙娜丽莎的眼泪 - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/091-mnlsdyl-gqq.m4a","264");
DATA("092.镜中的安娜 - 纯音乐（吉他)","http://index.asia.ga/?/cyy/wmcyy/092-jzdan-cyl(jt).m4a","265");
DATA("093.星语心愿 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/093-xyxy-cyl.m4a","266");
DATA("094.山不转水转 (萨克斯 )- 纯音乐","http://index.asia.ga/?/cyy/wmcyy/094-sbzsz(sks)-cyl.m4a","267");
DATA("095.治愈心灵的神曲 - 轻音乐","http://index.asia.ga/?/cyy/wmcyy/095-zyxldsq-qyl.m4a","268");
DATA("096.莫斯科郊外的晚上 - 萨克斯","http://index.asia.ga/?/cyy/wmcyy/096-mskjwdws-sks.m4a","269");
DATA("097.Lotus 莲花 - 神秘园","http://index.asia.ga/?/cyy/wmcyy/097-lotuslh-smy.m4a","270");
DATA("098.一直很安静 伴奏 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/098-yzhajbz-cyl.m4a","271");
DATA("099.魂断蓝桥主题曲 - 萨克斯","http://index.asia.ga/?/cyy/wmcyy/099-hdlqztq-sks.m4a","272");
DATA("100.奥里诺科之梦 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/100-alnkzm-bdr.m4a","273");
DATA("101.Heartstrings 心弦 - 神秘园","http://index.asia.ga/?/cyy/wmcyy/101-heartstringsxx-smy.m4a","274");
DATA("102.伤感音乐 - 太多 (小提琴) - 轻音乐","http://index.asia.ga/?/cyy/wmcyy/102-sgyl-td(xtq)-qyl.m4a","275");
DATA("103.在那遥远的地方 - 吉他曲","http://index.asia.ga/?/cyy/wmcyy/103-znyyddf-jtq.m4a","276");
DATA("104.风居住的街道 - 矶村由纪子","http://index.asia.ga/?/cyy/wmcyy/104-fjzdjd-jcyjz.m4a","277");
DATA("105.后来 (小提琴 长笛) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/105-hl(xtqcd)-cyl.m4a","278");
DATA("106.中央台天气预报背景音乐 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/106-zyttqybbjyl-cyl.m4a","279");
DATA("107.月光下漫舞 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/107-ygxmw-cyl.m4a","280");
DATA("108.流行的云 - 吉他纯音乐","http://index.asia.ga/?/cyy/wmcyy/108-lxdy-jtcyl.m4a","281");
DATA("109.踏古 - 林海 （琵琶）","http://index.asia.ga/?/cyy/wmcyy/109-tg-lh(pp).m4a","282");
DATA("110.流动的城市 - 林海 （钢琴曲）","http://index.asia.ga/?/cyy/wmcyy/110-lddcs-lh(gqq).m4a","283");
DATA("111.杨柳 - 林海","http://index.asia.ga/?/cyy/wmcyy/111-yl-lh.m4a","284");
DATA("112.林海 - 暗香","http://index.asia.ga/?/cyy/wmcyy/112-lh-ax.m4a","285");
DATA("113.火星金星 (Mars And Venus) - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/113-hxjx(marsandvenus)-bdr.m4a","286");
DATA("114.新不了情主题曲 - 纯音乐（萨克斯）","http://index.asia.ga/?/cyy/wmcyy/114-xblqztq-cyl(sks).m4a","287");
DATA("115.那天的遇见 (钢琴曲) - 赵海洋","http://index.asia.ga/?/cyy/wmcyy/115-ntdyj(gqq)-zhy.m4a","288");
DATA("116.纯音乐 - 橄榄树","http://index.asia.ga/?/cyy/wmcyy/116-cyl-gls.m4a","289");
DATA("117.风的誓言 (風の誓い) - 梁邦彦","http://index.asia.ga/?/cyy/wmcyy/117-fdsy-lby.m4a","290");
DATA("118.幽灵公主 - 轻音乐","http://index.asia.ga/?/cyy/wmcyy/118-ylgz-qyl.m4a","291");
DATA("119.雨的旋律 (中西器乐合璧) - 古筝","http://index.asia.ga/?/cyy/wmcyy/119-ydxl(zxqlhb)-gz.m4a","292");
DATA("120.往事 Ride On - Phil Coulter","http://index.asia.ga/?/cyy/wmcyy/120-wsrideon-philcoulter.m4a","293");
DATA("121.一起走过的日子 - 古筝","http://index.asia.ga/?/cyy/wmcyy/121-yqzgdrz-gz.m4a","294");
DATA("122.印度琵琶之魂 - 缪晓铮","http://index.asia.ga/?/cyy/wmcyy/122-ydppzh-mxz.m4a","295");
DATA("123.好听古典音乐 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/123-htgdyl-cyl.m4a","296");
DATA("124.在我心中的夏天 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/124-zwxzdxt-cyl.m4a","297");
DATA("125.青空下的约定 - 伊藤贤治","http://index.asia.ga/?/cyy/wmcyy/125-qkxdyd-ytxz.m4a","298");
DATA("126.罗多伦咖啡店 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/126-ldlkfd-cyl.m4a","299");
DATA("127.Moon River 月亮河","http://index.asia.ga/?/cyy/wmcyy/127-moonriverylh.m4a","300");
DATA("128.君生我未生 (我生君已老) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/128-jswws(wsjyl)-cyl.m4a","301");
DATA("129.醉人的钢琴声- 纯音乐","http://index.asia.ga/?/cyy/wmcyy/129-zrdgqs-cyl.m4a","302");
DATA("130.珍爱时光 (The Moment) - Kenny G","http://index.asia.ga/?/cyy/wmcyy/130-zasg(themoment)-kennyg.m4a","303");
DATA("131.无法超越的灵魂音乐 (乱红) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/131-wfcydlhyl(lh)-cyl.m4a","304");
DATA("132.追梦人 (雪山飞狐主题曲) - 笛子","http://index.asia.ga/?/cyy/wmcyy/132-zmr(xsfhztq)-dz.m4a","305");
DATA("133.娜迪亚主旋律 - Chris Phillips","http://index.asia.ga/?/cyy/wmcyy/133-ndyzxl-chrisphillips.m4a","306");
DATA("134.Chaconne 恰空舞曲 - 神秘园","http://index.asia.ga/?/cyy/wmcyy/134-chaconneqkwq-smy.m4a","307");
DATA("135.莲语的呢喃 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/135-lydnn-cyl.m4a","308");
DATA("136.-卷珠帘》意境钢琴版 - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/136-jzl-yjgqb-gqq.m4a","309");
DATA("137.欲望(Touch of Desire) (琵琶,吟唱) - 吕秀龄","http://index.asia.ga/?/cyy/wmcyy/137-yw(touchofdesire)(ppyc)-lxl.m4a","310");
DATA("138.我梦见了你 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/138-wmjln-cyl.m4a","311");
DATA("139.珍宝 (The Treasure) - Bernward Koch","http://index.asia.ga/?/cyy/wmcyy/139-zb(thetreasure)-bernwardkoch.m4a","312");
DATA("140.Your Eyes 你的眼神 - Andrew Jasinski","http://index.asia.ga/?/cyy/wmcyy/140-youreyesndys-andrewjasinski.m4a","313");
DATA("141.Down By The Salley Gardens (莎莉花园) - James Galway","http://index.asia.ga/?/cyy/wmcyy/141-downbythesalleygardens(slhy)-jamesgalway.m4a","314");
DATA("142.婚礼钟声 (Wedding Bell 吉他曲) - Depapepe","http://index.asia.ga/?/cyy/wmcyy/142-hlzs(weddingbelljtq)-depapepe.m4a","315");
DATA("143.浪客剑心 (Departure 钢琴+吉他) - 日本ACG","http://index.asia.ga/?/cyy/wmcyy/143-lkjx(departuregq+jt)-rbacg.m4a","316");
DATA("144.阿兰胡埃斯之爱 (优美的长笛) - Patrick Gallois","http://index.asia.ga/?/cyy/wmcyy/144-alhasza(ymdcd)-patrickgallois.m4a","317");
DATA("145.风光秀丽的小岛 (La Isla Bonita) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/145-fgxldxd(laislabonita)-cyl.m4a","318");
DATA("146.大千世界(钢琴) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/146-dqsj(gq)-cyl.m4a","319");
DATA("147.送别 - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/147-sb-gqq.m4a","320");
DATA("148.穿越时空的思念 - 和田薰","http://index.asia.ga/?/cyy/wmcyy/148-cyskdsn-htx.m4a","321");
DATA("149.通往幸福的路 (Path To Happiness) - Kondor","http://index.asia.ga/?/cyy/wmcyy/149-twxfdl(pathtohappiness)-kondor.m4a","322");
DATA("150.永远同在 - 宗次郎","http://index.asia.ga/?/cyy/wmcyy/150-yytz-zcl.m4a","323");
DATA("151.闪烁的星星 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/151-ssdxx-cyl.m4a","324");
DATA("152.威尼斯天使 (Forever after) - 竖琴","http://index.asia.ga/?/cyy/wmcyy/152-wnsts(foreverafter)-sq.m4a","325");
DATA("153.唯美浪漫的纯音乐 N°025 - Relaxdaily","http://index.asia.ga/?/cyy/wmcyy/153-wmlmdcyln-relaxdaily.m4a","326");
DATA("154.在那遥远的地方 (萨克斯) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/154-znyyddf(sks)-cyl.m4a","327");
DATA("155.盛开成花树 - 喵步小雨中","http://index.asia.ga/?/cyy/wmcyy/155-skchs-mbxyz.m4a","328");
DATA("156.生活的乐趣 (The Joy Of Life) - Kenny G","http://index.asia.ga/?/cyy/wmcyy/156-shdlq(thejoyoflife)-kennyg.m4a","329");
DATA("157.风之诗 - 吉他名曲","http://index.asia.ga/?/cyy/wmcyy/157-fzs-jtmq.m4a","330");
DATA("158.爱尔兰晨风(笛) - 陈悦","http://index.asia.ga/?/cyy/wmcyy/158-aelcf(d)-cy.m4a","331");
DATA("159.Memories 回忆 - Wendi","http://index.asia.ga/?/cyy/wmcyy/159-memorieshy-wendi.m4a","332");
DATA("160.晴了的某日 - 全素妍","http://index.asia.ga/?/cyy/wmcyy/160-qldmr-qsy.m4a","333");
DATA("161.在你的怀抱中最安全 - Kevin Kern","http://index.asia.ga/?/cyy/wmcyy/161-zndhbzzaq-kevinkern.m4a","334");
DATA("162.天际 (大自然音乐) - Mickey Lee","http://index.asia.ga/?/cyy/wmcyy/162-tj(dzryl)-mickeylee.m4a","335");
DATA("163.流星雨 - 陈冠宇","http://index.asia.ga/?/cyy/wmcyy/163-lxy-cgy.m4a","336");
DATA("164.约定 - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/164-yd-gqq.m4a","337");
DATA("165.奥里诺科之梦 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/165-alnkzm-bdr.m4a","338");
DATA("166.变幻之风 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/166-bhzf-bdr.m4a","339");
DATA("167.星际安魂曲 - 山下直人","http://index.asia.ga/?/cyy/wmcyy/167-xjahq-sxzr.m4a","340");
DATA("168.风车 (Wind-mill) - Andemund Orchestra","http://index.asia.ga/?/cyy/wmcyy/168-fc(wind-mill)-andemundorchestra.m4a","341");
DATA("169.雨空 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/169-yk-cyl.m4a","342");
DATA("170.春野 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/170-cy-bdr.m4a","343");
DATA("171.华丽的节奏钢琴 (Midnight Affair) - Tom Barabas","http://index.asia.ga/?/cyy/wmcyy/171-hldjzgq(midnightaffair)-tombarabas.m4a","344");
DATA("172.秘密的庭院 (钢琴轻音乐) - 理查德","http://index.asia.ga/?/cyy/wmcyy/172-mmdty(gqqyl)-lcd.m4a","345");
DATA("173.精灵之吻 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/173-jlzw-bdr.m4a","346");
DATA("174.满天星 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/174-mtx-bdr.m4a","347");
DATA("175.迷雾水珠 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/175-mwsz-bdr.m4a","348");
DATA("176.秘密 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/176-mm-bdr.m4a","349");
DATA("177.森林中的一夜 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/177-slzdyy-bdr.m4a","350");
DATA("178.我心深处 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/178-wxsc-bdr.m4a","351");
DATA("179.印地安之梦 - 班得瑞","http://index.asia.ga/?/cyy/wmcyy/179-ydazm-bdr.m4a","352");
DATA("180.蓝色星球 - Guido Negraszus","http://index.asia.ga/?/cyy/wmcyy/180-lsxq-guidonegraszus.m4a","353");
DATA("181.我的歌声里 - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/181-wdgsl-gqq.m4a","354");
DATA("182.Moon Flow (听起来十分舒畅) - Nomak","http://index.asia.ga/?/cyy/wmcyy/182-moonflow(tqlsfsc)-nomak.m4a","355");
DATA("183.Autumn Journey 秋之旅 - Eric Chiryoku","http://index.asia.ga/?/cyy/wmcyy/183-autumnjourneyqzl-ericchiryoku.m4a","356");
DATA("184.无尽之雨 (唯美钢琴曲) - 林有三","http://index.asia.ga/?/cyy/wmcyy/184-wjzy(wmgqq)-lys.m4a","357");
DATA("185.夏恋 - Otokaze","http://index.asia.ga/?/cyy/wmcyy/185-xl-otokaze.m4a","358");
DATA("186.夏日星 (Summer Star) - Lanx","http://index.asia.ga/?/cyy/wmcyy/186-xrx(summerstar)-lanx.m4a","359");
DATA("187.轻松的古典小夜曲 (Serenade) - Andre Rieu","http://index.asia.ga/?/cyy/wmcyy/187-qsdgdxyq(serenade)-andrerieu.m4a","360");
DATA("188.海阔天空 - 钢琴","http://index.asia.ga/?/cyy/wmcyy/188-hktk-gq.m4a","361");
DATA("189.森林之歌 Forest Hymn - Bill Douglas","http://index.asia.ga/?/cyy/wmcyy/189-slzgforesthymn-billdouglas.m4a","362");
DATA("190.没有夜晚（There Is No Night） - Mairead Nesbitt","http://index.asia.ga/?/cyy/wmcyy/190-myyw(thereisnonight)-maireadnesbitt.m4a","363");
DATA("191.全心全意 (Heart and Soul) - Kenny G","http://index.asia.ga/?/cyy/wmcyy/191-qxqy(heartandsoul)-kennyg.m4a","364");
DATA("192.寂静之声 (吉他) - 明仔","http://index.asia.ga/?/cyy/wmcyy/192-jjzs(jt)-mz.m4a","365");
DATA("193.阿兰胡埃斯协奏曲 - Julian Bream","http://index.asia.ga/?/cyy/wmcyy/193-alhasxzq-julianbream.m4a","366");
DATA("194.Between Worlds (带有力量的宁静) - Roger Subirana","http://index.asia.ga/?/cyy/wmcyy/194-betweenworlds(dylldnj)-rogersubirana.m4a","367");
DATA("195.寂静之声 (吉他) - 明仔","http://index.asia.ga/?/cyy/wmcyy/195-jjzs(jt)-mz.m4a","368");
DATA("196.After the Rain (雨后) - Kevin Kern","http://index.asia.ga/?/cyy/wmcyy/196-aftertherain(yh)-kevinkern.m4a","369");
DATA("197.小酒窝钢琴版 - 王喆","http://index.asia.ga/?/cyy/wmcyy/197-xjwgqb-wz.m4a","370");
DATA("198.你的微笑 (Tu Sonrisa 微风吉他二重奏) - La Vienta","http://index.asia.ga/?/cyy/wmcyy/198-ndwx(tusonrisawfjtecz)-lavienta.m4a","371");
DATA("199.美丽的神话 - Pure Music","http://index.asia.ga/?/cyy/wmcyy/199-mldsh-puremusic.m4a","372");
DATA("200.季节的轮回 - 奥户巴寿","http://index.asia.ga/?/cyy/wmcyy/200-jjdlh-ahbs.m4a","373");
DATA("201.当我遇 - 甘仕良","http://index.asia.ga/?/cyy/wmcyy/201-dwy-gsl.m4a","374");
DATA("202.神秘园之歌 钢琴曲 - 赵海洋","http://index.asia.ga/?/cyy/wmcyy/202-smyzggqq-zhy.m4a","375");
DATA("203.玛奇朵飘浮 (手风琴) - 王雁盟","http://index.asia.ga/?/cyy/wmcyy/203-mqdpf(sfq)-wym.m4a","376");
DATA("204.落日大道 - Guido Negraszus","http://index.asia.ga/?/cyy/wmcyy/204-lrdd-guidonegraszus.m4a","377");
DATA("205.别说我的眼泪你无所谓 (钢琴) - 王喆","http://index.asia.ga/?/cyy/wmcyy/205-bswdylnwsw(gq)-wz.m4a","378");
DATA("206.秋～華恋～ - α·Pav","http://index.asia.ga/?/cyy/wmcyy/206-q-hl-apav.m4a","379");
DATA("207.你的心河 (River Flows In You) - Eisblume","http://index.asia.ga/?/cyy/wmcyy/207-ndxh(riverflowsinyou)-eisblume.m4a","380");
DATA("208.蓝色生死恋I主题曲 - Lawrence","http://index.asia.ga/?/cyy/wmcyy/208-lsssliztq-lawrence.m4a","381");
DATA("209.季节的女王 (The Queen Of Season) - Danbi","http://index.asia.ga/?/cyy/wmcyy/209-jjdnw(thequeenofseason)-danbi.m4a","382");
DATA("210.一起走过的日子(古筝) - 李炜","http://index.asia.ga/?/cyy/wmcyy/210-yqzgdrz(gz)-lw.m4a","383");
DATA("211.以思念 (十九岁的纯情背景音乐) - 钢琴曲","http://index.asia.ga/?/cyy/wmcyy/211-ysn(sjsdcqbjyl)-gqq.m4a","384");
DATA("212.Childhood's Memory 陶笛版 (思い出の小箱) - 宗次郎","http://index.asia.ga/?/cyy/wmcyy/212-childhoodsmemorytdb-zcl.m4a","385");
DATA("213.卡农 (小提琴) - 利未人室内乐团","http://index.asia.ga/?/cyy/wmcyy/213-kn(xtq)-lwrsnlt.m4a","386");
DATA("214.我在那一角落患过伤风 - 赵海洋","http://index.asia.ga/?/cyy/wmcyy/214-wznyjlhgsf-zhy.m4a","387");
DATA("215.Follow Your Heart (聆听心灵深处的呼唤) - Karunesh","http://index.asia.ga/?/cyy/wmcyy/215-followyourheart(ltxlscdhh)-karunesh.m4a","388");
DATA("216.微笑的弧度 (Silent Love) - 何真真","http://index.asia.ga/?/cyy/wmcyy/216-wxdhd(silentlove)-hzz.m4a","389");
DATA("217.花言叶 - α·Pav","http://index.asia.ga/?/cyy/wmcyy/217-hyy-apav.m4a","390");
DATA("218.欢乐的珍珠——凯文·科恩","http://index.asia.ga/?/cyy/wmcyy/218-hldzz-kwke.m4a","391");
DATA("219.生命之舞(钢琴与排笛) - Brad White & Pierre Grill","http://index.asia.ga/?/cyy/wmcyy/219-smzw(gqypd)-bradwhite&pierregrill.m4a","392");
DATA("220.希望曙光 - 喵步小雨中","http://index.asia.ga/?/cyy/wmcyy/220-xwsg-mbxyz.m4a","393");
DATA("221.睁不开眼就看不见- 纯音乐","http://index.asia.ga/?/cyy/wmcyy/221-zbkyjkbj-cyl.m4a","394");
DATA("222.suiren - a_hisa","http://index.asia.ga/?/cyy/wmcyy/222-suiren-a_hisa.m4a","395");
DATA("223.游戏-蓝莓花园》的原声集 (Entre deux) - Daduk","http://index.asia.ga/?/cyy/wmcyy/223-yx-lmhy-dysj(entredeux)-daduk.m4a","396");
DATA("224.善良的心 - Marc Enfroy","http://index.asia.ga/?/cyy/wmcyy/224-sldx-marcenfroy.m4a","397");
DATA("225.梦中见——凯文·科恩","http://index.asia.ga/?/cyy/wmcyy/225-mzj-kwke.m4a","398");
DATA("226.久远~光和波的记忆~ -日本ACG","http://index.asia.ga/?/cyy/wmcyy/226-jy-ghbdjy-rbacg.m4a","399");
DATA("227.雪花颂E (Snow Flower Song E) - Sweet Rain","http://index.asia.ga/?/cyy/wmcyy/227-xhse(snowflowersonge)-sweetrain.m4a","400");
DATA("228.爱的记忆- Phil Coulter","http://index.asia.ga/?/cyy/wmcyy/228-adjy-philcoulter.m4a","401");
DATA("229.醉梦西班牙 - Aage Kvalbein","http://index.asia.ga/?/cyy/wmcyy/229-zmxby-aagekvalbein.m4a","402");
DATA("230.舒伯特：天鹅之歌 (小夜曲) - Arthur Grumiaux","http://index.asia.ga/?/cyy/wmcyy/230-sbt：tezg(xyq)-arthurgrumiaux.m4a","403");
DATA("231.Numb 钢琴版 - 林肯公园","http://index.asia.ga/?/cyy/wmcyy/231-numbgqb-lkgy.m4a","404");
DATA("232.ひだまりの（向阳之乡） - 日本ACG","http://index.asia.ga/?/cyy/wmcyy/232-xyzx-rbacg.m4a","405");
DATA("233.Palace Memories~Sunset - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/233-palacememories-sunset-cyl.m4a","406");
DATA("234.Your Beautiful Love - Back to Earth","http://index.asia.ga/?/cyy/wmcyy/234-yourbeautifullove-backtoearth.m4a","407");
DATA("235.暗恋过结局呢(节奏) - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/235-algjjn(jz)-cyl.m4a","408");
DATA("236.悲歌 Cancion Triste - Jesse Cook","http://index.asia.ga/?/cyy/wmcyy/236-bgcanciontriste-jessecook.m4a","409");
DATA("237.小夜曲 - 舒伯特","http://index.asia.ga/?/cyy/wmcyy/237-xyq-sbt.m4a","410");
DATA("238.跨越时代的思念 (钢琴曲) - 和田薰","http://index.asia.ga/?/cyy/wmcyy/238-kysddsn(gqq)-htx.m4a","411");
DATA("239.我爱你 Ya Tebya Lubliu (吉他) - Acoustic Alchemy","http://index.asia.ga/?/cyy/wmcyy/239-wanyatebyalubliu(jt)-acousticalchemy.m4a","412");
DATA("240.散花 - Key Sounds Label","http://index.asia.ga/?/cyy/wmcyy/240-sh-keysoundslabel.m4a","413");
DATA("241.Lost my pieces (龙与虎 感人配乐) - 桥本由香利","http://index.asia.ga/?/cyy/wmcyy/241-lostmypieces(lyhgrpl)-qbyxl.m4a","414");
DATA("242.Do You Live, Do You Love (活着而爱着) - Danny Wright","http://index.asia.ga/?/cyy/wmcyy/242-doyoulivedoyoulove(hzeaz)-dannywright.m4a","415");
DATA("243.Pachebel's Canon in D (卡农钢琴曲) - Danny Wright","http://index.asia.ga/?/cyy/wmcyy/243-pachebelscanonind(kngqq)-dannywright.m4a","416");
DATA("244.Sleepless beauty (万有引力) - 浅仑大介","http://index.asia.ga/?/cyy/wmcyy/244-sleeplessbeauty(wyyl)-qldj.m4a","417");
DATA("245.河西走廊之梦-雅尼","http://index.asia.ga/?/cyy/wmcyy/245-hxzlzm-yn.m4a","418");
DATA("246.如果我能告诉你-雅尼","http://index.asia.ga/?/cyy/wmcyy/246-rgwngsn-yn.m4a","419");
DATA("247.当星星落下时-安菲尔","http://index.asia.ga/?/cyy/wmcyy/247-dxxlxs-afe.m4a","420");
DATA("248.雨中漫步-雅尼","http://index.asia.ga/?/cyy/wmcyy/248-yzmb-yn.m4a","421");
DATA("249.永远不会太晚-雅尼","http://index.asia.ga/?/cyy/wmcyy/249-yybhtw-yn.m4a","422");
DATA("250.一直在我心中 - Udo Vismann","http://index.asia.ga/?/cyy/wmcyy/250-yzzwxz-udovismann.m4a","423");
DATA("251.秋天的色彩 - Soothing Relaxation","http://index.asia.ga/?/cyy/wmcyy/251-qtdsc-soothingrelaxation.m4a","424");
DATA("252.Always 永远 - Soothing Relaxation","http://index.asia.ga/?/cyy/wmcyy/252-alwaysyy-soothingrelaxation.m4a","425");
DATA("253.绿袖子 (Greensleeves) - 理查德","http://index.asia.ga/?/cyy/wmcyy/253-lxz(greensleeves)-lcd.m4a","426");
DATA("254.胡伟立 - 温馨时刻","http://index.asia.ga/?/cyy/wmcyy/254-hwl-wxsk.m4a","427");
DATA("255.纯音乐 - 莫失莫忘","http://index.asia.ga/?/cyy/wmcyy/255-cyl-msmw.m4a","428");
DATA("256.胡伟立 - 雪千寻","http://index.asia.ga/?/cyy/wmcyy/256-hwl-xqx.m4a","429");
DATA("257.如梦岁月-纯音乐","http://index.asia.ga/?/cyy/wmcyy/257-rmsy-cyl.m4a","430");
DATA("258.刹那永恒-纯音乐","http://index.asia.ga/?/cyy/wmcyy/258-snyh-cyl.m4a","431");
DATA("259.秋的思念 - 纯音乐","http://index.asia.ga/?/cyy/wmcyy/259-qdsn-cyl.m4a","432");
DATA("260.中华通络操-纯音乐","http://index.asia.ga/?/cyy/wmcyy/260-zhtlc-cyl.m4a","433");
DATA("261.我和我的祖国-钢琴曲","http://index.asia.ga/?/cyy/wmcyy/261-whwdzg-gqq.m4a","434");
DATA("262.我爱你中国 -小提琴","http://index.asia.ga/?/cyy/wmcyy/262-wanzg-xtq.m4a","435");
DATA("263.如烟长廊-吉他","http://index.asia.ga/?/cyy/wmcyy/263-rycl-jt.m4a","436");
DATA("264.牧羊曲","http://index.asia.ga/?/cyy/wmcyy/264-myq.m4a","437");
DATA("265.AIR-青空（钢琴版）","http://index.asia.ga/?/cyy/wmcyy/265-air-qk(gqb).m4a","438");
DATA("266.青空","http://index.asia.ga/?/cyy/wmcyy/266-qk.m4a","439");
DATA("267.空纳万境","http://index.asia.ga/?/cyy/wmcyy/267-knwj.m4a","440");
DATA("268.告白の夜","http://index.asia.ga/?/cyy/wmcyy/268-gbdy.m4a","441");
DATA("269.幻昼","http://index.asia.ga/?/cyy/wmcyy/269-hz.m4a","442");
DATA("270.风平浪静","http://index.asia.ga/?/cyy/wmcyy/270-fplj.m4a","443");
DATA("271.夜、萤火虫和你","http://index.asia.ga/?/cyy/wmcyy/271-y-yhchn.m4a","444");
DATA("272.一人静","http://index.asia.ga/?/cyy/wmcyy/272-yrj.m4a","445");
DATA("273.岩山---昭乌达盟民歌","http://index.asia.ga/?/cyy/wmcyy/273-ys-zwdmmg.m4a","446");
DATA("274.Einsamer Hirte 孤独的牧羊人 ( 口琴 )","http://index.asia.ga/?/cyy/wmcyy/274-einsamerhirtegddmyr(kq).m4a","447");
DATA("275.Heavenly (feat. Felicia Farerre)","http://index.asia.ga/?/cyy/wmcyy/275-heavenly(feat-feliciafarerre).m4a","448");
DATA("276.心绪 Continuous Thought","http://index.asia.ga/?/cyy/wmcyy/276-xxcontinuousthought.m4a","449");
DATA("277.打雷下雨的声音真好听","http://index.asia.ga/?/cyy/wmcyy/277-dlxydsyzht.m4a","450");
DATA("278.痴情冢 【笛子版】","http://index.asia.ga/?/cyy/wmcyy/278-cqzdzb.m4a","451");
DATA("279.someone like you 原版伴奏","http://index.asia.ga/?/cyy/wmcyy/279-someonelikeyouybbz.m4a","452");
DATA("280.雨碎江南，花影斑斓-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/280-ysjnhybl-wmcyl.m4a","453");
DATA("281.茶","http://index.asia.ga/?/cyy/wmcyy/281-c.m4a","454");
DATA("282.好听的古典音乐","http://index.asia.ga/?/cyy/wmcyy/282-htdgdyl.m4a","455");
DATA("283.桃花渡","http://index.asia.ga/?/cyy/wmcyy/283-thd.m4a","456");
DATA("284.临安初雨，春水凝碧-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/284-lacycsnb-wmcyl.m4a","457");
DATA("285.探清水河","http://index.asia.ga/?/cyy/wmcyy/285-tqsh.m4a","458");
DATA("286.云海间","http://index.asia.ga/?/cyy/wmcyy/286-yhj.m4a","459");
DATA("287.山野幽居，宁静幽谧-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/287-syyjnjym-wmcyl.m4a","460");
DATA("288.苍竹滴翠，寂然如水-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/288-czdcjrrs-wmcyl.m4a","461");
DATA("289.回想-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/289-hx-wmcyl.m4a","462");
DATA("290.琵琶行-钢琴曲","http://index.asia.ga/?/cyy/wmcyy/290-ppx-gqq.m4a","463");
DATA("291.三个人的时光","http://index.asia.ga/?/cyy/wmcyy/291-sgrdsg.m4a","464");
DATA("292.繁华的寂静-钢琴曲","http://index.asia.ga/?/cyy/wmcyy/292-fhdjj-gqq.m4a","465");
DATA("293.秋来风起，叶落禅意-唯美轻音乐","http://index.asia.ga/?/cyy/wmcyy/293-qlfqylcy-wmqyl.m4a","466");
DATA("294.伴读静心唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/294-bdjxwmcyl.m4a","467");
DATA("295.那些关于你的爱恨情长","http://index.asia.ga/?/cyy/wmcyy/295-nxgyndahqc.m4a","468");
DATA("296.那个你熟悉且难忘的声音 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/296-ngnsxqnwdsy-wmcyl.m4a","469");
DATA("297.雨韵悠然，滋润心田- 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/297-yyyrzrxt-wmcyl.m4a","470");
DATA("298.千年一叹，婉韵悠远（古筝） - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/298-qnytwyyy(gz)-wmcyl.m4a","471");
DATA("299.水姻缘（古筝新韵）-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/299-syy(gzxy)-wmcyl.m4a","472");
DATA("300.女儿情 （古筝） - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/300-neq(gz)-wmcyl.m4a","473");
DATA("301.水-禅意名曲 (茶禅一味) - 唯美轻音乐","http://index.asia.ga/?/cyy/wmcyy/301-s-cymq(ccyw)-wmqyl.m4a","474");
DATA("302.睡莲（二胡）-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/302-sl(eh)-wmcyl.m4a","475");
DATA("303.碧玉的江孜（净化心灵的西藏乐曲）- 纯音乐","http://index.asia.ga/?/cyy/wmcyy/303-bydjz(jhxldxclq)-cyl.m4a","476");
DATA("304.潮汐的旋律，心灵的慰藉 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/304-cxdxlxldwj-wmcyl.m4a","477");
DATA("305.天籁之音,来自印第安 -唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/305-tlzylzyda-wmcyl.m4a","478");
DATA("306.花开不记年-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/306-hkbjn-wmcyl.m4a","479");
DATA("307.姻缘（古典）-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/307-yy(gd)-wmcyl.m4a","480");
DATA("308.墨兰香，韵悠扬-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/308-mlxyyy-wmcyl.m4a","481");
DATA("309.天籁排箫 最后的莫西干人","http://index.asia.ga/?/cyy/wmcyy/309-tlpxzhdmxgr.m4a","482");
DATA("310.织女·心丝 (笛箫版) - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/310-znxs(dxb)-wmcyl.m4a","483");
DATA("311.风云依旧，人已老 (钢琴曲) - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/311-fyyjryl(gqq)-wmcyl.m4a","484");
DATA("312.下雨的时候（小提琴） -唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/312-xydsh(xtq)-wmcyl.m4a","485");
DATA("313.红颜旧，此情不忘，忍别离 (笛子版)-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/313-hyjcqbwrbl(dzb)-wmcyl.m4a","486");
DATA("314.-水墨兰亭》沉静如水，静逸如诗-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/314-smlt-cjrsjyrs-wmcyl.m4a","487");
DATA("315.司岗里情，相依相望-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/315-sglqxyxw-wmcyl.m4a","488");
DATA("316.江南印象，隽永舒畅-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/316-jnyxjysc-wmcyl.m4a","489");
DATA("317.薰衣草的阴影-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/317-xycdyy-wmcyl.m4a","490");
DATA("318.缘聚 （醉人的水墨中国风）-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/318-yj(zrdsmzgf)-wmcyl.m4a","491");
DATA("319.绾青丝，别离殇（二胡）唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/319-wqsbls(eh)wmcyl.m4a","492");
DATA("320.玉烟笛梦，诉说人生-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/320-yydmssrs-wmcyl.m4a","493");
DATA("321.是谁在你耳畔呢喃-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/321-ssznepnn-wmcyl.m4a","494");
DATA("322.相恋在夏季-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/322-xlzxj-wmcyl.m4a","495");
DATA("323.曾经追梦，现已不年轻-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/323-zjzmxybnq-wmcyl.m4a","496");
DATA("324.爱恨离别，梁祝化蝶 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/324-ahlblzhd-wmcyl.m4a","497");
DATA("325.时光如流沙，珍惜当下 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/325-sgrlszxdx-wmcyl.m4a","498");
DATA("326.世外桃源 ，飘逸幽远 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/326-swtypyyy-wmcyl.m4a","499");
DATA("327.放空自己，心灵之旅- 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/327-fkzjxlzl-wmcyl.m4a","500");
DATA("328.深山禅林，幽远意境 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/328-ssclyyyj-wmcyl.m4a","501");
DATA("329.尽余欢，今宵别梦寒-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/329-jyhjxbmh-wmcyl.m4a","502");
DATA("330.-静水禅音》静心极乐 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/330-jscy-jxjl-wmcyl.m4a","503");
DATA("331.佛号静心，涤荡红尘-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/331-fhjxddhc-wmcyl.m4a","504");
DATA("332.月下起舞（傣族民乐）-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/332-yxqw(dzml)-wmcyl.m4a","505");
DATA("333.生活安详，舟渔晚唱 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/333-shaxzywc-wmcyl.m4a","506");
DATA("334.万水千山总是情 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/334-wsqszsq-wmcyl.m4a","507");
DATA("335.湖光水面，宁静幽远 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/335-hgsmnjyy-wmcyl.m4a","508");
DATA("336.旭日清晨，唯美醉人 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/336-xrqcwmzr-wmcyl.m4a","509");
DATA("337.流水潺潺，筝音婉转-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/337-lscczywz-wmcyl.m4a","510");
DATA("338.别样晚秋，是喜是忧-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/338-bywqsxsy-wmcyl.m4a","511");
DATA("339.恢弘史诗，大气磅礴-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/339-hhssdqbb-wmcyl.m4a","512");
DATA("340.岁月华章，再现辉煌-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/340-syhzzxhh-wmcyl.m4a","513");
DATA("341.不变的心，永恒的爱-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/341-bbdxyhda-wmcyl.m4a","514");
DATA("342.梦里水乡，让人向往 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/342-mlsxrrxw-wmcyl.m4a","515");
DATA("343.且听风吟 ，触动人心 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/343-qtfycdrx-wmcyl.m4a","516");
DATA("344.安静养心，舒缓心情 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/344-ajyxshxq-wmcyl.m4a","517");
DATA("345.永浴爱河 ，至真至深- 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/345-yyahzzzs-wmcyl.m4a","518");
DATA("346.真爱永恒，相伴一生 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/346-zayhxbys-wmcyl.m4a","519");
DATA("347.青春短暂，让人怀念 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/347-qcdzrrhn-wmcyl.m4a","520");
DATA("348.一曲一净土，一弦一清心 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/348-yqyjtyxyqx-wmcyl.m4a","521");
DATA("349.余生很短，请别错过 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/349-yshdqbcg-wmcyl.m4a","522");
DATA("350.秋叶珊珊，伴君入眠 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/350-qyssbjrm-wmcyl.m4a","523");
DATA("351.竹笛声悠扬，和夜莺很像-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/351-zdsyyhyyhx-wmcyl.m4a","524");
DATA("352.音符跳动，抚慰心灵-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/352-yftdfwxl-wmcyl.m4a","525");
DATA("353.灵魂的呼唤，雄鹰之歌-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/353-lhdhhxyzg-wmcyl.m4a","526");
DATA("354.英雄落寞，悲壮豪迈-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/354-yxlmbzhm-wmcyl.m4a","527");
DATA("355.清新自然，雪的梦幻 - 唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/355-qxzrxdmh-wmcyl.m4a","528");
DATA("356.失去你，我会迷失-唯美纯音乐","http://index.asia.ga/?/cyy/wmcyy/356-sqnwhms-wmcyl.m4a","529");
DATA("001.阵雨（雨声、电视卡顿、钢琴、马林巴、弦乐器、竖琴、钢片琴）","http://index.asia.ga/?/cyy/zrzs/001-zy(ys-dskd-gq-mlb-xlq-sq-gpq).m4a","530");
DATA("002.下雨天（下雨、钢琴、钢片琴、长笛、单簧管）","http://index.asia.ga/?/cyy/zrzs/002-xyt(xy-gq-gpq-cd-dhg).m4a","531");
DATA("003.山里农家（风吹稻田、鸟鸣、马林巴、钢片琴、钢琴、弦乐器）","http://index.asia.ga/?/cyy/zrzs/003-slnj(fcdt-nm-mlb-gpq-gq-xlq).m4a","532");
DATA("004.心语（海浪、钢琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/004-xy(hl-gq-dtq).m4a","533");
DATA("005.梦见你（呼吸声、呼噜声、钢琴、弦乐器）","http://index.asia.ga/?/cyy/zrzs/005-mjn(hxs-hls-gq-xlq).m4a","534");
DATA("006.小晴（潮汐、鸟鸣、马林巴、钢琴、钢片琴）","http://index.asia.ga/?/cyy/zrzs/006-xq(cx-nm-mlb-gq-gpq).m4a","535");
DATA("007.下班（轨道的当啷声、脚步声、吉他、钟琴、贝斯、长笛、架子鼓、钢琴）","http://index.asia.ga/?/cyy/zrzs/007-xb(gdddls-jbs-jt-zq-bs-cd-jzg-gq).m4a","536");
DATA("008.雨季（雨声、马林巴、钢片琴、竖琴）","http://index.asia.ga/?/cyy/zrzs/008-yj(ys-mlb-gpq-sq).m4a","537");
DATA("009.再遇（雨声、钢琴、马林巴、管风琴、竖琴、弦乐、小钹）","http://index.asia.ga/?/cyy/zrzs/009-zy(ys-gq-mlb-gfq-sq-xl-xb).m4a","538");
DATA("010.渔歌（钓鱼、水流、竖琴）","http://index.asia.ga/?/cyy/zrzs/010-yg(dy-sl-sq).m4a","539");
DATA("011.摇篮（潮汐、虫鸣、钢琴)","http://index.asia.ga/?/cyy/zrzs/011-yl(cx-cm-gq).m4a","540");
DATA("012.轻轻的脚步声（鸟鸣、狗吠、脚步声、钢琴）","http://index.asia.ga/?/cyy/zrzs/012-qqdjbs(nm-gf-jbs-gq).m4a","541");
DATA("013.等你（下雨、拨打电话、钢琴、马林巴、竖琴、钢片琴）","http://index.asia.ga/?/cyy/zrzs/013-dn(xy-bddh-gq-mlb-sq-gpq).m4a","542");
DATA("014.长路慢行（海浪、钢琴、长笛、弦乐器、钢片琴）","http://index.asia.ga/?/cyy/zrzs/014-clmx(hl-gq-cd-xlq-gpq).m4a","543");
DATA("015.凉风有信（淅淅沥沥的下雨、脚步声、钢琴、马林巴、钟琴）","http://index.asia.ga/?/cyy/zrzs/015-lfyx(xxlldxy-jbs-gq-mlb-zq).m4a","544");
DATA("016.为你撑伞（雨水、吉他、竖琴）","http://index.asia.ga/?/cyy/zrzs/016-wncs(ys-jt-sq).m4a","545");
DATA("017.房前清泉（泉水叮咚、钢琴）","http://index.asia.ga/?/cyy/zrzs/017-fqqq(qsdd-gq).m4a","546");
DATA("018.浪漫篝火（篝火、钢琴、长笛、双簧管、贝斯）","http://index.asia.ga/?/cyy/zrzs/018-lmgh(gh-gq-cd-shg-bs).m4a","547");
DATA("019.从前慢（虫鸣、钢琴、大提琴、钢片琴）","http://index.asia.ga/?/cyy/zrzs/019-cqm(cm-gq-dtq-gpq).m4a","548");
DATA("020.我爱我家（猫咪、篝火、钢琴、钢片琴）","http://index.asia.ga/?/cyy/zrzs/020-wawj(mm-gh-gq-gpq).m4a","549");
DATA("021.蒲公英的幻想（溪水、鸟鸣、钢琴）","http://index.asia.ga/?/cyy/zrzs/021-pgydhx(xs-nm-gq).m4a","550");
DATA("022.流水潺潺（溪水、竖琴、钢琴、钢片琴、钟琴）","http://index.asia.ga/?/cyy/zrzs/022-lscc(xs-sq-gq-gpq-zq).m4a","551");
DATA("023.在月亮下跳舞吧（清风、雨水、钢琴）","http://index.asia.ga/?/cyy/zrzs/023-zylxtwb(qf-ys-gq).m4a","552");
DATA("024.像从前那样（虫鸣、鸟鸣、钢琴、和声）","http://index.asia.ga/?/cyy/zrzs/024-xcqny(cm-nm-gq-hs).m4a","553");
DATA("025.夏风之声（潮汐、蝉鸣、钢琴）","http://index.asia.ga/?/cyy/zrzs/025-xfzs(cx-cm-gq).m4a","554");
DATA("026.星星、月亮与满满（流水潺潺、钢琴）","http://index.asia.ga/?/cyy/zrzs/026-xx-ylymm(lscc-gq).m4a","555");
DATA("027.月光洒向海面（海水、浪花、钢琴）","http://index.asia.ga/?/cyy/zrzs/027-ygsxhm(hs-lh-gq).m4a","556");
DATA("028.闲逛（鸟鸣、水滴、脚步声、钢琴、长笛）","http://index.asia.ga/?/cyy/zrzs/028-xg(nm-sd-jbs-gq-cd).m4a","557");
DATA("029.踏上稻乡（鸟鸣、钢琴）","http://index.asia.ga/?/cyy/zrzs/029-tsdx(nm-gq).m4a","558");
DATA("030.我们的时光（时钟、钟琴、钢琴）","http://index.asia.ga/?/cyy/zrzs/030-wmdsg(sz-zq-gq).m4a","559");
DATA("031.仲夏夜的梦境（蟋蟀鸟鸣、钢琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/031-zxydmj(xsnm-gq-dtq).m4a","560");
DATA("032.湛蓝天空（流水声、鸟鸣、萨克斯、钢琴）","http://index.asia.ga/?/cyy/zrzs/032-zltk(lss-nm-sks-gq).m4a","561");
DATA("033.乡间小路（林中清溪、竖笛、大提琴）","http://index.asia.ga/?/cyy/zrzs/033-xjxl(lzqx-sd-dtq).m4a","562");
DATA("034.澄澈心灵（夏夜蟋蟀蝉鸣、大提琴、钢琴、木吉他）","http://index.asia.ga/?/cyy/zrzs/034-ccxl(xyxscm-dtq-gq-mjt).m4a","563");
DATA("035.路在前方（鸟鸣、钢琴、木吉他、大提琴）","http://index.asia.ga/?/cyy/zrzs/035-lzqf(nm-gq-mjt-dtq).m4a","564");
DATA("036.早安（鸟鸣、钢琴）","http://index.asia.ga/?/cyy/zrzs/036-za(nm-gq).m4a","565");
DATA("037.秘境岛屿（海浪、长笛、木吉他）","http://index.asia.ga/?/cyy/zrzs/037-mjdy(hl-cd-mjt).m4a","566");
DATA("038.老街（山涧鸟鸣、钢琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/038-lj(sjnm-gq-dtq).m4a","567");
DATA("039.悠闲假期（流水、鸟鸣、木吉他、钢琴、提琴）","http://index.asia.ga/?/cyy/zrzs/039-yxjq(ls-nm-mjt-gq-tq).m4a","568");
DATA("040.宁静港湾（水边鸟鸣、木吉他、钢琴）","http://index.asia.ga/?/cyy/zrzs/040-njgw(sbnm-mjt-gq).m4a","569");
DATA("041.在花园里劳作（浇水、狗吠、钢琴）","http://index.asia.ga/?/cyy/zrzs/041-zhyllz(js-gf-gq).m4a","570");
DATA("042.放下烦忧（海浪、木吉他、大提琴）","http://index.asia.ga/?/cyy/zrzs/042-fxfy(hl-mjt-dtq).m4a","571");
DATA("043.时光的痕迹（沥沥小雨、纯钢琴）","http://index.asia.ga/?/cyy/zrzs/043-sgdhj(llxy-cgq).m4a","572");
DATA("044.黎明（溪水潺潺、钢琴）","http://index.asia.ga/?/cyy/zrzs/044-lm(xscc-gq).m4a","573");
DATA("045.送别（风声、流水、钢琴、提琴、口琴）","http://index.asia.ga/?/cyy/zrzs/045-sb(fs-ls-gq-tq-kq).m4a","574");
DATA("046.小森林（鸟鸣、树叶、钢片琴、马林巴、长笛、竖琴、小提琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/046-xsl(nm-sy-gpq-mlb-cd-sq-xtq-dtq).m4a","575");
DATA("047.心若无尘（水波、竖琴、短笛）","http://index.asia.ga/?/cyy/zrzs/047-xrwc(sb-sq-dd).m4a","576");
DATA("048.远走（鸟鸣、钢琴、提琴）","http://index.asia.ga/?/cyy/zrzs/048-yz(nm-gq-tq).m4a","577");
DATA("049.流星花园（鸟鸣、孩子笑声、钢琴、贝斯、钢片琴、大提琴、小提琴、中提琴）","http://index.asia.ga/?/cyy/zrzs/049-lxhy(nm-hzxs-gq-bs-gpq-dtq-xtq-ztq).m4a","578");
DATA("050.兜风（脚步声、汽车、风声、电子琴、马林巴、钢片琴）","http://index.asia.ga/?/cyy/zrzs/050-df(jbs-qc-fs-dzq-mlb-gpq).m4a","579");
DATA("051.小可爱（宝宝笑声、钢琴、钢片琴、长笛、黑管）","http://index.asia.ga/?/cyy/zrzs/051-xka(bbxs-gq-gpq-cd-hg).m4a","580");
DATA("052.舞动的花朵（风、鸟鸣、钢琴、钟琴、马林巴、钢片琴）","http://index.asia.ga/?/cyy/zrzs/052-wddhd(f-nm-gq-zq-mlb-gpq).m4a","581");
DATA("053.明天之后（微风、长笛、钢琴）","http://index.asia.ga/?/cyy/zrzs/053-mtzh(wf-cd-gq).m4a","582");
DATA("054.家乡（脚步声、电车、钢琴、贝斯、钟琴）","http://index.asia.ga/?/cyy/zrzs/054-jx(jbs-dc-gq-bs-zq).m4a","583");
DATA("055.躲雨（雨声、钢琴）","http://index.asia.ga/?/cyy/zrzs/055-dy(ys-gq).m4a","584");
DATA("056.寻找自我之旅（鸟鸣、自行车、钢琴）","http://index.asia.ga/?/cyy/zrzs/056-xzzwzl(nm-zxc-gq).m4a","585");
DATA("057.冬至（落叶、钢琴、长笛、单簧管）","http://index.asia.ga/?/cyy/zrzs/057-dz(ly-gq-cd-dhg).m4a","586");
DATA("058.暖暖的东风（鸟鸣、脚步声、钢琴、钟琴）","http://index.asia.ga/?/cyy/zrzs/058-nnddf(nm-jbs-gq-zq).m4a","587");
DATA("059.壁炉（火苗、小猫、钢琴、弦乐器）","http://index.asia.ga/?/cyy/zrzs/059-bl(hm-xm-gq-xlq).m4a","588");
DATA("060.梦游记（虫鸣、弦乐四重奏、钢琴）","http://index.asia.ga/?/cyy/zrzs/060-myj(cm-xlscz-gq).m4a","589");
DATA("061.我们一家人（鸟鸣、小狗、小猫、钢琴、贝斯）","http://index.asia.ga/?/cyy/zrzs/061-wmyjr(nm-xg-xm-gq-bs).m4a","590");
DATA("062.冬日清晨（流水、竖琴、长笛、钢片琴）","http://index.asia.ga/?/cyy/zrzs/062-drqc(ls-sq-cd-gpq).m4a","591");
DATA("063.蓝色海岸线（海浪、潮汐、钢琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/063-lshax(hl-cx-gq-dtq).m4a","592");
DATA("064.从冬眠中醒来（流水、钢琴、钟琴、长笛）","http://index.asia.ga/?/cyy/zrzs/064-cdmzxl(ls-gq-zq-cd).m4a","593");
DATA("065.当春天来到（鸟鸣、钢琴）","http://index.asia.ga/?/cyy/zrzs/065-dctld(nm-gq).m4a","594");
DATA("066.森林晨景（鸟鸣、宝宝学语声、木吉他、钢琴、长笛）","http://index.asia.ga/?/cyy/zrzs/066-slcj(nm-bbxys-mjt-gq-cd).m4a","595");
DATA("067.向着光亮那方（流水、鸟鸣、钢琴、长笛）","http://index.asia.ga/?/cyy/zrzs/067-xzglnf(ls-nm-gq-cd).m4a","596");
DATA("068.夜晚的星（蟋蟀、虫鸣、钢琴）","http://index.asia.ga/?/cyy/zrzs/068-ywdx(xs-cm-gq).m4a","597");
DATA("069.日不落（蛙鸣、木吉他、钢琴）","http://index.asia.ga/?/cyy/zrzs/069-rbl(wm-mjt-gq).m4a","598");
DATA("070.喜鹊成双（水波、深山鸟鸣、爵士钢琴、萨克斯）","http://index.asia.ga/?/cyy/zrzs/070-xqcs(sb-ssnm-jsgq-sks).m4a","599");
DATA("071.夏日微风（习习凉风、宝宝笑声、纯钢琴）","http://index.asia.ga/?/cyy/zrzs/071-xrwf(xxlf-bbxs-cgq).m4a","600");
DATA("072.万事顺心（鸟鸣、风声、水声、钢琴、小提琴）","http://index.asia.ga/?/cyy/zrzs/072-wssx(nm-fs-ss-gq-xtq).m4a","601");
DATA("073.晨思前奏曲（篝火冉冉、纯钢琴）","http://index.asia.ga/?/cyy/zrzs/073-csqzq(ghrr-cgq).m4a","602");
DATA("074.从你的全世界路过（海鸟、潮汐、钢琴）","http://index.asia.ga/?/cyy/zrzs/074-cndqsjlg(hn-cx-gq).m4a","603");
DATA("075.世界尽头与冷酷仙境（海风、波涛、钢琴、提琴）","http://index.asia.ga/?/cyy/zrzs/075-sjjtylkxj(hf-bt-gq-tq).m4a","604");
DATA("076.想见你（缓缓流水、钢琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/076-xjn(hhls-gq-dtq).m4a","605");
DATA("077.牵牛花（啾啾鸟鸣、钢琴）","http://index.asia.ga/?/cyy/zrzs/077-qnh(jjnm-gq).m4a","606");
DATA("078.雨后的天空（春雷、蛙鸣、钢琴）","http://index.asia.ga/?/cyy/zrzs/078-yhdtk(cl-wm-gq).m4a","607");
DATA("079.日出（早晨山顶、钢琴、竖笛）","http://index.asia.ga/?/cyy/zrzs/079-rc(zcsd-gq-sd).m4a","608");
DATA("080.山顶日出（流水声、手风琴、短笛、提琴）","http://index.asia.ga/?/cyy/zrzs/080-sdrc(lss-sfq-dd-tq).m4a","609");
DATA("081.念念回首（涟漪、翠鸟声、纯钢琴）","http://index.asia.ga/?/cyy/zrzs/081-nnhs(ly-cns-cgq).m4a","610");
DATA("082.江河共余生（鸟鸣、微风、钢琴、小提琴）","http://index.asia.ga/?/cyy/zrzs/082-jhgys(nm-wf-gq-xtq).m4a","611");
DATA("083.待凛冬离去（春日鸟鸣、钢琴、小提琴）","http://index.asia.ga/?/cyy/zrzs/083-dldlq(crnm-gq-xtq).m4a","612");
DATA("084.候鸟的生活（森林鸟鸣、钢琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/084-hndsh(slnm-gq-dtq).m4a","613");
DATA("085.星河长明（仲夏虫鸣、纯钢琴）","http://index.asia.ga/?/cyy/zrzs/085-xhcm(zxcm-cgq).m4a","614");
DATA("086.晚歌（虫鸣、纯钢琴）","http://index.asia.ga/?/cyy/zrzs/086-wg(cm-cgq).m4a","615");
DATA("087.萤火虫之歌（虫鸣、钢琴、竖琴）","http://index.asia.ga/?/cyy/zrzs/087-yhczg(cm-gq-sq).m4a","616");
DATA("088.童年梦境（蟋蟀、虫鸣、纯钢琴）","http://index.asia.ga/?/cyy/zrzs/088-tnmj(xs-cm-cgq).m4a","617");
DATA("089.童年梦境（蟋蟀、虫鸣、纯钢琴）","http://index.asia.ga/?/cyy/zrzs/089-tnmj(xs-cm-cgq).m4a","618");
DATA("090.漂浮的云（鸟鸣、钢琴、八音盒、小提琴）","http://index.asia.ga/?/cyy/zrzs/090-pfdy(nm-gq-byh-xtq).m4a","619");
DATA("091.风平浪静（柔情海浪、大提琴、铁琴）","http://index.asia.ga/?/cyy/zrzs/091-fplj(rqhl-dtq-tq).m4a","620");
DATA("092.一路向北（风浪、长笛、小提琴、钢琴）","http://index.asia.ga/?/cyy/zrzs/092-ylxb(fl-cd-xtq-gq).m4a","621");
DATA("093.飘雪（风浪、钢琴、木吉他、小提琴）","http://index.asia.ga/?/cyy/zrzs/093-px(fl-gq-mjt-xtq).m4a","622");
DATA("094.风中的信（蟋蟀、晚风、钢琴、小提琴）","http://index.asia.ga/?/cyy/zrzs/094-fzdx(xs-wf-gq-xtq).m4a","623");
DATA("095.日落的时候（山野虫鸣、木吉他、钢琴、小提琴）","http://index.asia.ga/?/cyy/zrzs/095-rldsh(sycm-mjt-gq-xtq).m4a","624");
DATA("096.心安（缓缓流水、微风、竖琴、长笛、钢琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/096-xa(hhls-wf-sq-cd-gq-dtq).m4a","625");
DATA("097.爱你 是我做过最好的事（水波、鸟鸣、木吉他、钢琴）","http://index.asia.ga/?/cyy/zrzs/097-answzgzhds(sb-nm-mjt-gq).m4a","626");
DATA("098.看海（海浪、海鸟、木吉他、钢琴）","http://index.asia.ga/?/cyy/zrzs/098-kh(hl-hn-mjt-gq).m4a","627");
DATA("099.我好想你（微风习习、钢琴、木吉他）","http://index.asia.ga/?/cyy/zrzs/099-whxn(wfxx-gq-mjt).m4a","628");
DATA("100.青青草原的傍晚（3D音效、虫鸣、短笛、竖琴）","http://index.asia.ga/?/cyy/zrzs/100-qqcydbw(3dyx-cm-dd-sq).m4a","629");
DATA("101.湖畔夜色（3D湖水声、鸟鸣、萨克斯、钢琴）","http://index.asia.ga/?/cyy/zrzs/101-hpys(3dhss-nm-sks-gq).m4a","630");
DATA("102.潮起潮落（海风、海浪、钢琴）","http://index.asia.ga/?/cyy/zrzs/102-cqcl(hf-hl-gq).m4a","631");
DATA("103.夏天的故事（山林声音、钢琴）","http://index.asia.ga/?/cyy/zrzs/103-xtdgs(slsy-gq).m4a","632");
DATA("104.春天森林（大自然声音、钢琴、木吉他、大提琴、小提琴）","http://index.asia.ga/?/cyy/zrzs/104-ctsl(dzrsy-gq-mjt-dtq-xtq).m4a","633");
DATA("105.月亮的梦（3D音效、雷雨、八音盒）戴耳机听更妙噢","http://index.asia.ga/?/cyy/zrzs/105-yldm(3dyx-ly-byh)dejtgmo.m4a","634");
DATA("106.风雨之后彩虹漫天（3D音效、雷雨、钢琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/106-fyzhchmt(3dyx-ly-gq-dtq).m4a","635");
DATA("107.山涧小溪缓缓流淌（3D纯大自然声音）","http://index.asia.ga/?/cyy/zrzs/107-sjxxhhlt(3dcdzrsy).m4a","636");
DATA("108.窗外大海（温柔海浪、3D脑波音乐）","http://index.asia.ga/?/cyy/zrzs/108-cwdh(wrhl-3dnbyl).m4a","637");
DATA("109.静夜思（3D舒睡轻音乐）","http://index.asia.ga/?/cyy/zrzs/109-jys(3dssqyl).m4a","638");
DATA("110.朝幸福奔去（3D舒睡轻音乐）","http://index.asia.ga/?/cyy/zrzs/110-cxfbq(3dssqyl).m4a","639");
DATA("111.人间最美是安静（3D纯音乐）","http://index.asia.ga/?/cyy/zrzs/111-rjzmsaj(3dcyl).m4a","640");
DATA("112.森林雨后（涓涓溪流、钢琴、大提琴）","http://index.asia.ga/?/cyy/zrzs/112-slyh(jjxl-gq-dtq).m4a","641");
DATA("113.天冷了给你拥抱（3D风声、八音盒）","http://index.asia.ga/?/cyy/zrzs/113-tllgnyb(3dfs-byh).m4a","642");
DATA("114.愿你快乐无忧（海浪、八音盒、钢琴）","http://index.asia.ga/?/cyy/zrzs/114-ynklwy(hl-byh-gq).m4a","643");
DATA("115.彼岸烟火（3D舒眠纯音乐）","http://index.asia.ga/?/cyy/zrzs/115-bayh(3dsmcyl).m4a","644");
DATA("116.回到过去（浪花、钢琴、竖笛、大提琴）","http://index.asia.ga/?/cyy/zrzs/116-hdgq(lh-gq-sd-dtq).m4a","645");
DATA("117.北极的风（3D纯大自然声音）","http://index.asia.ga/?/cyy/zrzs/117-bjdf(3dcdzrsy).m4a","646");
DATA("118.心事如浮萍（3D安眠轻音乐）","http://index.asia.ga/?/cyy/zrzs/118-xsrfp(3damqyl).m4a","647");
DATA("119.水滴声声（3D舒眠大自然轻音乐）","http://index.asia.ga/?/cyy/zrzs/119-sdss(3dsmdzrqyl).m4a","648");
DATA("120.牵着你的手到世界尽头（3D晚安轻音乐）","http://index.asia.ga/?/cyy/zrzs/120-qzndsdsjjt(3dwaqyl).m4a","649");
DATA("121.深海中的水流（3D纯大自然声音）","http://index.asia.ga/?/cyy/zrzs/121-shzdsl(3dcdzrsy).m4a","650");
DATA("122.窗外是雨天（3D纯音乐）","http://index.asia.ga/?/cyy/zrzs/122-cwsyt(3dcyl).m4a","651");
DATA("123.为你留了一盏灯（3D纯音乐）","http://index.asia.ga/?/cyy/zrzs/123-wnllyzd(3dcyl).m4a","652");
DATA("124.星空下的篝火（3D大自然声音）","http://index.asia.ga/?/cyy/zrzs/124-xkxdgh(3ddzrsy).m4a","653");
DATA("125.呼吸在海平面下10米（3D大自然声音）","http://index.asia.ga/?/cyy/zrzs/125-hxzhpmx10m(3ddzrsy).m4a","654");
DATA("126.水下气泡（3D大自然声音）","http://index.asia.ga/?/cyy/zrzs/126-sxqp(3ddzrsy).m4a","655");
DATA("127.海上栈桥","http://index.asia.ga/?/cyy/zrzs/127-hszq.m4a","656");
DATA("128.回家的路","http://index.asia.ga/?/cyy/zrzs/128-hjdl.m4a","657");
DATA("129.夏夜","http://index.asia.ga/?/cyy/zrzs/129-xy.m4a","658");
DATA("130.夏日绿荫","http://index.asia.ga/?/cyy/zrzs/130-xrly.m4a","659");
DATA("131.海边微风起","http://index.asia.ga/?/cyy/zrzs/131-hbwfq.m4a","660");
DATA("132.海鸥岛","http://index.asia.ga/?/cyy/zrzs/132-hod.m4a","661");
DATA("133.大海","http://index.asia.ga/?/cyy/zrzs/133-dh.m4a","662");
DATA("134.山野","http://index.asia.ga/?/cyy/zrzs/134-sy.m4a","663");
DATA("135.泉眼无声惜细流","http://index.asia.ga/?/cyy/zrzs/135-qywsxxl.m4a","664");
DATA("136.风吹雨成夏","http://index.asia.ga/?/cyy/zrzs/136-fcycx.m4a","665");
DATA("137.雷雨","http://index.asia.ga/?/cyy/zrzs/137-ly.m4a","666");
DATA("138.北极","http://index.asia.ga/?/cyy/zrzs/138-bj.m4a","667");
DATA("139.山涧","http://index.asia.ga/?/cyy/zrzs/139-sj.m4a","668");
DATA("140.划船","http://index.asia.ga/?/cyy/zrzs/140-hc.m4a","669");
DATA("141.海底世界","http://index.asia.ga/?/cyy/zrzs/141-hdsj.m4a","670");
DATA("142.篝火","http://index.asia.ga/?/cyy/zrzs/142-gh.m4a","671");
DATA("143.山顶日落","http://index.asia.ga/?/cyy/zrzs/143-sdrl.m4a","672");
DATA("144.雪地","http://index.asia.ga/?/cyy/zrzs/144-xd.m4a","673");
DATA("145.林中小溪","http://index.asia.ga/?/cyy/zrzs/145-lzxx.m4a","674");
DATA("146.走在沙滩上","http://index.asia.ga/?/cyy/zrzs/146-zzsts.m4a","675");
DATA("147.小森林","http://index.asia.ga/?/cyy/zrzs/147-xsl.m4a","676");
DATA("148.小可爱","http://index.asia.ga/?/cyy/zrzs/148-xka.m4a","677");
DATA("149.舞动的花朵","http://index.asia.ga/?/cyy/zrzs/149-wddhd.m4a","678");
DATA("150.回归校园","http://index.asia.ga/?/cyy/zrzs/150-hgxy.m4a","679");
DATA("151.从冬眠中醒来","http://index.asia.ga/?/cyy/zrzs/151-cdmzxl.m4a","680");
DATA("152.当春天来到","http://index.asia.ga/?/cyy/zrzs/152-dctld.m4a","681");
DATA("153.家乡","http://index.asia.ga/?/cyy/zrzs/153-jx.m4a","682");
DATA("154.早春","http://index.asia.ga/?/cyy/zrzs/154-zc.m4a","683");
DATA("155.冬日清晨","http://index.asia.ga/?/cyy/zrzs/155-drqc.m4a","684");
DATA("156.妈妈的厨房","http://index.asia.ga/?/cyy/zrzs/156-mmdcf.m4a","685");
DATA("157.初夏","http://index.asia.ga/?/cyy/zrzs/157-cx.m4a","686");
DATA("158.破晓","http://index.asia.ga/?/cyy/zrzs/158-px.m4a","687");
DATA("159.我们一家人","http://index.asia.ga/?/cyy/zrzs/159-wmyjr.m4a","688");
DATA("160.流星花园","http://index.asia.ga/?/cyy/zrzs/160-lxhy.m4a","689");
DATA("161.雪之华","http://index.asia.ga/?/cyy/zrzs/161-xzh.m4a","690");
DATA("162.暖暖的东风","http://index.asia.ga/?/cyy/zrzs/162-nnddf.m4a","691");
DATA("163.平安夜","http://index.asia.ga/?/cyy/zrzs/163-pay.m4a","692");
DATA("164.星语心愿","http://index.asia.ga/?/cyy/zrzs/164-xyxy.m4a","693");
DATA("165.雪落下的声音","http://index.asia.ga/?/cyy/zrzs/165-xlxdsy.m4a","694");
DATA("166.初雪","http://index.asia.ga/?/cyy/zrzs/166-cx.m4a","695");
DATA("167.梦见你","http://index.asia.ga/?/cyy/zrzs/167-mjn.m4a","696");
DATA("168.轻轻的脚步声","http://index.asia.ga/?/cyy/zrzs/168-qqdjbs.m4a","697");
DATA("169.下班","http://index.asia.ga/?/cyy/zrzs/169-xb.m4a","698");
DATA("170.冬至","http://index.asia.ga/?/cyy/zrzs/170-dz.m4a","699");
DATA("171.我爱我家","http://index.asia.ga/?/cyy/zrzs/171-wawj.m4a","700");
DATA("172.蓝色海岸线","http://index.asia.ga/?/cyy/zrzs/172-lshax.m4a","701");
DATA("173.淋雨一直走","http://index.asia.ga/?/cyy/zrzs/173-lyyzz.m4a","702");
DATA("174.下个路口","http://index.asia.ga/?/cyy/zrzs/174-xglk.m4a","703");
DATA("175.山里农家","http://index.asia.ga/?/cyy/zrzs/175-slnj.m4a","704");
DATA("176.梦游记","http://index.asia.ga/?/cyy/zrzs/176-myj.m4a","705");
DATA("177.旅行的诗","http://index.asia.ga/?/cyy/zrzs/177-lxds.m4a","706");
DATA("178.渔歌","http://index.asia.ga/?/cyy/zrzs/178-yg.m4a","707");
DATA("179.浪漫篝火","http://index.asia.ga/?/cyy/zrzs/179-lmgh.m4a","708");
DATA("180.壁炉","http://index.asia.ga/?/cyy/zrzs/180-bl.m4a","709");
DATA("181.凉风有信","http://index.asia.ga/?/cyy/zrzs/181-lfyx.m4a","710");
DATA("182.等你回来","http://index.asia.ga/?/cyy/zrzs/182-dnhl.m4a","711");
DATA("183.此刻的温柔","http://index.asia.ga/?/cyy/zrzs/183-ckdwr.m4a","712");
DATA("184.从前慢","http://index.asia.ga/?/cyy/zrzs/184-cqm.m4a","713");
DATA("185.长路慢行","http://index.asia.ga/?/cyy/zrzs/185-clmx.m4a","714");
DATA("186.冬眠","http://index.asia.ga/?/cyy/zrzs/186-dm.m4a","715");
DATA("187.再遇","http://index.asia.ga/?/cyy/zrzs/187-zy.m4a","716");
DATA("188.种星星的人","http://index.asia.ga/?/cyy/zrzs/188-zxxdr.m4a","717");
DATA("189.好想你","http://index.asia.ga/?/cyy/zrzs/189-hxn.m4a","718");
DATA("190.流水潺潺","http://index.asia.ga/?/cyy/zrzs/190-lscc.m4a","719");
DATA("191.心语","http://index.asia.ga/?/cyy/zrzs/191-xy.m4a","720");
DATA("192.海底总动员","http://index.asia.ga/?/cyy/zrzs/192-hdzdy.m4a","721");
DATA("193.寻找自我之旅","http://index.asia.ga/?/cyy/zrzs/193-xzzwzl.m4a","722");
DATA("194.老电影","http://index.asia.ga/?/cyy/zrzs/194-ldy.m4a","723");
DATA("195.雨城","http://index.asia.ga/?/cyy/zrzs/195-yc.m4a","724");
DATA("196.在水一方","http://index.asia.ga/?/cyy/zrzs/196-zsyf.m4a","725");
DATA("197.仲夏夜之梦","http://index.asia.ga/?/cyy/zrzs/197-zxyzm.m4a","726");
DATA("198.直到春天过去","http://index.asia.ga/?/cyy/zrzs/198-zdctgq.m4a","727");
DATA("199.等你","http://index.asia.ga/?/cyy/zrzs/199-dn.m4a","728");
DATA("200.阵雨","http://index.asia.ga/?/cyy/zrzs/200-zy.m4a","729");
DATA("201.闲逛","http://index.asia.ga/?/cyy/zrzs/201-xg.m4a","730");
DATA("202.小晴","http://index.asia.ga/?/cyy/zrzs/202-xq.m4a","731");
DATA("203.躲雨","http://index.asia.ga/?/cyy/zrzs/203-dy.m4a","732");
DATA("204.兜风","http://index.asia.ga/?/cyy/zrzs/204-df.m4a","733");
DATA("205.雨季","http://index.asia.ga/?/cyy/zrzs/205-yj.m4a","734");
DATA("206.下雨天","http://index.asia.ga/?/cyy/zrzs/206-xyt.m4a","735");
DATA("207.为你撑伞","http://index.asia.ga/?/cyy/zrzs/207-wncs.m4a","736");
DATA("208.我们的时光","http://index.asia.ga/?/cyy/zrzs/208-wmdsg.m4a","737");
DATA("209.早安","http://index.asia.ga/?/cyy/zrzs/209-za.m4a","738");
DATA("210.在花园里劳作","http://index.asia.ga/?/cyy/zrzs/210-zhyllz.m4a","739");
DATA("211.雨中蛙声 - 雨下大了蛙声也渐渐变小","http://index.asia.ga/?/cyy/zrzs/211-yzws-yxdlwsyjjbx.m4a","740");
DATA("212.雨后-树下的雨滴稀稀疏疏","http://index.asia.ga/?/cyy/zrzs/212-yh-sxdydxxss.m4a","741");
DATA("213.下雨天 - 车里无转向灯 带耳机效果超赞","http://index.asia.ga/?/cyy/zrzs/213-xyt-clwzxddejxgcz.m4a","742");
DATA("214.下雨天 - 车里打着转向灯 带耳机效果超赞","http://index.asia.ga/?/cyy/zrzs/214-xyt-cldzzxddejxgcz.m4a","743");
DATA("215.棕叶下的雨 关注声谷 众公号了解自然录音","http://index.asia.ga/?/cyy/zrzs/215-zyxdygzsgzghljzrly.m4a","744");
DATA("216.深夜的雨声 大自然声音","http://index.asia.ga/?/cyy/zrzs/216-sydysdzrsy.m4a","745");
DATA("217.深夜林中细雨 大自然的声音 纯音乐","http://index.asia.ga/?/cyy/zrzs/217-sylzxydzrdsycyl.m4a","746");
DATA("218.雨声行人鸟儿飞机 舒适自然 大自然的声音 纯音乐","http://index.asia.ga/?/cyy/zrzs/218-ysxrnefjsszrdzrdsycyl.m4a","747");
DATA("219.亭子下的雨声 大自然的声音 纯音乐［声谷］","http://index.asia.ga/?/cyy/zrzs/219-tzxdysdzrdsycylsg.m4a","748");
DATA("220.台风来时 大自然的声音 纯音乐［声谷］","http://index.asia.ga/?/cyy/zrzs/220-tflsdzrdsycylsg.m4a","749");
DATA("221.云栖竹林听雨 午后禅定 大自然的声音 纯音乐 [声谷]","http://index.asia.ga/?/cyy/zrzs/221-yqzltywhcddzrdsycylsg.m4a","750");
DATA("222.清晨的雨声 大自然的声音 纯音乐［声谷］","http://index.asia.ga/?/cyy/zrzs/222-qcdysdzrdsycylsg.m4a","751");
